-- OpenClaw sessions map CloudHub ownership to one durable OpenClaw
-- session. IDs are generated by CloudHub and stored as text like the existing
-- PostgreSQL-backed Guardian resources.
CREATE TABLE IF NOT EXISTS openclaw_sessions (
    id                   text        PRIMARY KEY,
    organization_id      text        NOT NULL,
    user_id              text        NOT NULL,
    agent_id             text        NOT NULL,
    openclaw_session_key text        NOT NULL,
    title                text        NOT NULL DEFAULT '',
    created_at           timestamptz NOT NULL,
    updated_at           timestamptz NOT NULL,
    UNIQUE (organization_id, user_id, id),
    UNIQUE (openclaw_session_key)
);

-- Session lists are always owner-scoped and newest activity first.
CREATE INDEX IF NOT EXISTS openclaw_sessions_owner_idx
    ON openclaw_sessions (organization_id, user_id, updated_at DESC);
