import {
  ROUTER_TABLE_SIZING,
  TOPSOURCES_TABLE_SIZING,
  TOPSESSIONS_TABLE_SIZING,
} from 'src/addon/128t/constants/tableSizing'
import {GET_ALLROUTERS_INFO} from 'src/addon/128t/constants/query'

export {
  ROUTER_TABLE_SIZING,
  TOPSOURCES_TABLE_SIZING,
  TOPSESSIONS_TABLE_SIZING,
  GET_ALLROUTERS_INFO,
}
