export const ROUTER_TABLE_SIZING = {
  ASSETID: 'calc(13% - 30px)',
  LOCATIONCOORDINATES: '8%',
  MANAGEMENTCONNECTED: '8%',
  BANDWIDTH_AVG: '8%',
  SESSION_CNT_AVG: '5%',
  ENABLED: '8%',
  ROLE: '8%',
  STARTTIME: '10%',
  SOFTWAREVERSION: '8%',
  MEMORYUSAGE: '8%',
  CPUUSAGE: '8%',
  DISKUSAGE: '8%',
  CHECKBOX: '30px',
}

export const TOPSOURCES_TABLE_SIZING = {
  IP: 'calc(34% - 100px)',
  TENANT: '20%',
  CURRENTBANDWIDTH: '23%',
  TOTALDATA: '23%',
  SESSIONCOUNT: '100px',
}

export const TOPSESSIONS_TABLE_SIZING = {
  TOPSESSION_SERVICE: '20%',
  TOPSESSION_TENANT: '10%',
  TOPSESSION_VALUE: '8%',
  TOPSESSION_PROTOCOL: '8%',
  TOPSESSION_SOURCE_ADDRESS: '19%',
  TOPSESSION_SOURCE_PORT: '8%',
  TOPSESSION_DESTINATION_ADDRESS: '19%',
  TOPSESSION_DESTINATION_PORT: '8%',
}
