export const ROUTER_TABLE_SIZING = {
  ASSETID: 'calc(23% - 240px)',
  LOCATIONCOORDINATES: '12%',
  MANAGEMENTCONNECTED: '120px',
  BANDWIDTH_AVG: '8%',
  SESSION_CNT_AVG: '8%',
  ENABLED: '120px',
  ROLE: '5%',
  STARTTIME: '12%',
  SOFTWAREVERSION: '8%',
  MEMORYUSAGE: '8%',
  CPUUSAGE: '8%',
  DISKUSAGE: '8%',
}

export const TOPSOURCES_TABLE_SIZING = {
  IP: '30%',
  TENANT: '30%',
  CURRENTBANDWIDTH: '15%',
  TOTALDATA: '15%',
  SESSIONCOUNT: '10%',
}

export const TOPSESSIONS_TABLE_SIZING = {
  TOPSESSION_SERVICE: '30%',
  TOPSESSION_TENANT: '20%',
  TOPSESSION_VALUE: '5%',
  TOPSESSION_PROTOCOL: '5%',
  TOPSESSION_SOURCE_ADDRESS: '10%',
  TOPSESSION_SOURCE_PORT: '10%',
  TOPSESSION_DESTINATION_ADDRESS: '10%',
  TOPSESSION_DESTINATION_PORT: '10%',
}
