export const ROUTER_TABLE_SIZING = {
  CHECKBOX: '30px',
  NODENAME: 'calc(13% - 30px)',
  GROUP: '8%',
  IPADDRESS: '10%',
  LOCATIONCOORDINATES: '6%',
  MANAGEMENTCONNECTED: '6%',
  BANDWIDTH_AVG: '8%',
  SESSION_CNT_AVG: '5%',
  ENABLED: '6%',
  ROLE: '8%',
  STARTTIME: '10%',
  SOFTWAREVERSION: '6%',
  MEMORYUSAGE: '8%',
  CPUUSAGE: '8%',
  DISKUSAGE: '8%',
}

export const TOPSOURCES_TABLE_SIZING = {
  IP: 'calc(34% - 100px)',
  TENANT: '20%',
  CURRENTBANDWIDTH: '23%',
  TOTALDATA: '23%',
  SESSIONCOUNT: '100px',
}

export const TOPSESSIONS_TABLE_SIZING = {
  TOPSESSION_SERVICE: '20%',
  TOPSESSION_TENANT: '10%',
  TOPSESSION_VALUE: '8%',
  TOPSESSION_PROTOCOL: '8%',
  TOPSESSION_SOURCE_ADDRESS: '19%',
  TOPSESSION_SOURCE_PORT: '8%',
  TOPSESSION_DESTINATION_ADDRESS: '19%',
  TOPSESSION_DESTINATION_PORT: '8%',
}

export const ONCUE_SERVICE_TABLE_SIZING = {
  ONCUE_SERVICE_NAME: '18%',
  ONCUE_SERVICE_CPU: '10%',
  ONCUE_SERVICE_MEMORY: '10%',
  ONCUE_SERVICE_QUEUE: '10%',
  ONCUE_SERVICE_VERSION: '7%',
  ONCUE_SERVICE_STATUS: '8%',
  ONCUE_SERVICE_LISTENING_PORT: '8%',
  ONCUE_SERVICE_RUNNING_THREAD: '8%',
  ONCUE_SERVICE_PROCESSING_DATA_COUNT: '12%',
  ONCUE_SERVICE_PROCESSING_SPEED: '9%',
}

export const PROTOCOL_MODULES_TABLE_SIZING = {
  PROTOCOL_MODULES_NAME: '50%',
  PROTOCOL_MODULES_VERSION: '25%',
  PROTOCOL_MODULES_STATUS: '25%',
}

export const DEVICE_CONNECTIONS_TABLE_SIZING = {
  DEVICE_CONNECTIONS_URL: '100%',
}

export const CONNECTION_TABLE_SIZING = {
  CONNECTION_PATH_ID: '49%',
  CONNECTION_CONNECTED: '10%',
  CONNECTION_DISCONNECTED: '10%',
  CONNECTION_IN_USER: '8%',
  CONNECTION_DATA_COUNT: '15%',
  CONNECTION_SPEED: '8%',
}

export const TOPOLOGY_TABLE_SIZING = {
  TABLE_ROW_IN_HEADER: '47%',
  TABLE_ROW_IN_BODY: '53%',
}
