package protoboards

import (
	"context"
	"encoding/json"
	"fmt"

	cmp "github.com/snetsystems/cmp/backend"
)

//go:generate go-bindata -o bin_gen.go -ignore README|apps|.sh|go -pkg protoboards .

// BinProtoboardsStore represents a protoboards store using data generated by go-bindata
type BinProtoboardsStore struct {
	Logger cmp.Logger
}

// All returns the set of all protoboards
func (s *BinProtoboardsStore) All(ctx context.Context) ([]cmp.Protoboard, error) {
	names := AssetNames()
	protoboards := make([]cmp.Protoboard, len(names))
	for i, name := range names {
		octets, err := Asset(name)
		if err != nil {
			s.Logger.
				WithField("component", "protoboards").
				WithField("name", name).
				Error("Invalid protoboard: ", err)
			return nil, cmp.ErrProtoboardInvalid
		}

		var protoboard cmp.Protoboard
		if err = json.Unmarshal(octets, &protoboard); err != nil {
			s.Logger.
				WithField("component", "protoboards").
				WithField("name", name).
				Error("Unable to read protoboard:", err)
			return nil, cmp.ErrProtoboardInvalid
		}
		protoboards[i] = protoboard
	}

	return protoboards, nil
}

// Add is not support by BinProtoboardsStore
func (s *BinProtoboardsStore) Add(ctx context.Context, protoboard cmp.Protoboard) (cmp.Protoboard, error) {
	return cmp.Protoboard{}, fmt.Errorf("Add to BinProtoboardsStore not supported")
}

// Delete is not support by BinProtoboardsStore
func (s *BinProtoboardsStore) Delete(ctx context.Context, protoboard cmp.Protoboard) error {
	return fmt.Errorf("Delete to BinProtoboardsStore not supported")
}

// Get retrieves protoboard if `ID` exists.
func (s *BinProtoboardsStore) Get(ctx context.Context, ID string) (cmp.Protoboard, error) {
	protoboards, err := s.All(ctx)
	if err != nil {
		s.Logger.
			WithField("component", "protoboards").
			WithField("name", ID).
			Error("Invalid protoboard: ", err)
		return cmp.Protoboard{}, cmp.ErrProtoboardInvalid
	}

	for _, protoboard := range protoboards {
		if protoboard.ID == ID {
			return protoboard, nil
		}
	}

	s.Logger.
		WithField("component", "protoboards").
		WithField("name", ID).
		Error("protoboard not found")
	return cmp.Protoboard{}, cmp.ErrProtoboardNotFound
}

// Update not supported
func (s *BinProtoboardsStore) Update(ctx context.Context, protoboard cmp.Protoboard) error {
	return fmt.Errorf("Update to BinProtoboardsStore not supported")
}
