export const SUPPORTED_OS_VERSION = {
  SUPPORTED_CENTOS_VERSION: ['CentOS 7.X'],
  // SUPPORTED_UBUNTU_VERSION: ['Ubuntu 16.04', 'Ubuntu 18.04'],
  SUPPORTED_REDHAT_VERSION: ['RedHat 7.X'],
}

export const SUPPORTED_OS_VERSION_ORDER = [
  'SUPPORTED_CENTOS_VERSION',
  // 'SUPPORTED_UBUNTU_VERSION',
  'SUPPORTED_REDHAT_VERSION',
]
