import {
  NETWORK_ACCESS,
  GET_STATUS,
  SELECTBOX_TEXT,
} from 'src/agent_admin/constants/agentStatus'

import {
  AGENT_MINION_TABLE_SIZING,
  AGENT_CONFIGURATION_TABLE_SIZING,
  AGENT_CONTROL_TABLE_SIZING,
} from 'src/agent_admin/constants/tableSizing'

import {
  AGENT_COLLECTOR_DIRECTORY,
  AGENT_TENANT_DIRECTORY,
  AGENT_TENANT_CLOUD_DIRECTORY,
  AGENT_TELEGRAF_CONFIG,
} from 'src/agent_admin/constants/directory'

import {
  COLLECTOR_CONFIG_TABLE_DATA,
  COLLECTOR_DROPDOWN_DATA,
  COLLECTOR_CONFIG_TAB_ABBREVIATION,
  COLLECTOR_CONFIG_TAB_ORDER,
} from 'src/agent_admin/constants/CollectorConfigTable'

export {
  NETWORK_ACCESS,
  GET_STATUS,
  SELECTBOX_TEXT,
  AGENT_MINION_TABLE_SIZING,
  AGENT_CONFIGURATION_TABLE_SIZING,
  AGENT_CONTROL_TABLE_SIZING,
  AGENT_COLLECTOR_DIRECTORY,
  AGENT_TENANT_DIRECTORY,
  AGENT_TENANT_CLOUD_DIRECTORY,
  AGENT_TELEGRAF_CONFIG,
  COLLECTOR_CONFIG_TABLE_DATA,
  COLLECTOR_DROPDOWN_DATA,
  COLLECTOR_CONFIG_TAB_ABBREVIATION,
  COLLECTOR_CONFIG_TAB_ORDER,
}
