package builtin

import (
	"context"
	"encoding/json"
	"strings"
	"sync"

	cloudhub "github.com/snetsystems/cloudhub/backend"
)

//go:generate go-bindata -o bin_gen.go -ignore README|.md|go -pkg builtin ./dashboards ./alerts

// BinDashboardsStore represents a builtin dashboard store using data generated by go-bindata.
type BinDashboardsStore struct {
	Logger cloudhub.Logger
}

const dashboardAssetPrefix = "dashboards/"

// All returns the set of all builtin dashboards
func (s *BinDashboardsStore) All(ctx context.Context) ([]cloudhub.Dashboard, error) {
	names := AssetNames()
	var dashboards []cloudhub.Dashboard

	for _, name := range names {
		// Skip non-JSON files
		if !strings.HasPrefix(name, dashboardAssetPrefix) || !strings.HasSuffix(name, ".json") {
			continue
		}

		octets, err := Asset(name)
		if err != nil {
			s.Logger.
				WithField("component", "builtin").
				WithField("name", name).
				Error("Invalid Dashboard: ", err)
			continue // Skip invalid files instead of failing completely
		}

		var dashboard cloudhub.Dashboard
		if err = json.Unmarshal(octets, &dashboard); err != nil {
			s.Logger.
				WithField("component", "builtin").
				WithField("name", name).
				Error("Unable to read dashboard:", err)
			continue // Skip invalid files instead of failing completely
		}

		// Ensure type is set to builtin
		if dashboard.Type == "" {
			dashboard.Type = cloudhub.DashboardTypeBuiltin
		}

		dashboards = append(dashboards, dashboard)
	}

	return dashboards, nil
}

// Get retrieves a builtin dashboard by name
// Name should match the dashboard's Name field (e.g., "host_page")
func (s *BinDashboardsStore) Get(ctx context.Context, name string) (cloudhub.Dashboard, error) {
	dashboards, err := s.All(ctx)
	if err != nil {
		s.Logger.
			WithField("component", "builtin").
			WithField("name", name).
			Error("Invalid Dashboard: ", err)
		return cloudhub.Dashboard{}, cloudhub.ErrDashboardInvalid
	}

	for _, dashboard := range dashboards {
		if dashboard.Name == name {
			return dashboard, nil
		}
	}

	s.Logger.
		WithField("component", "builtin").
		WithField("name", name).
		Error("Dashboard not found")
	return cloudhub.Dashboard{}, cloudhub.ErrDashboardNotFound
}

// GetByFileName retrieves a builtin dashboard by its JSON file name (without extension)
// e.g., "hostpage" for "hostpage.json"
func (s *BinDashboardsStore) GetByFileName(ctx context.Context, fileName string) (cloudhub.Dashboard, error) {
	// Ensure fileName doesn't have .json extension
	fileName = strings.TrimSuffix(fileName, ".json")

	assetName := dashboardAssetPrefix + fileName + ".json"
	octets, err := Asset(assetName)
	if err != nil {
		s.Logger.
			WithField("component", "builtin").
			WithField("name", fileName).
			Error("Dashboard file not found: ", err)
		return cloudhub.Dashboard{}, cloudhub.ErrDashboardNotFound
	}

	var dashboard cloudhub.Dashboard
	if err = json.Unmarshal(octets, &dashboard); err != nil {
		s.Logger.
			WithField("component", "builtin").
			WithField("name", fileName).
			Error("Unable to read dashboard:", err)
		return cloudhub.Dashboard{}, cloudhub.ErrDashboardInvalid
	}

	// Ensure type is set to builtin
	if dashboard.Type == "" {
		dashboard.Type = cloudhub.DashboardTypeBuiltin
	}

	return dashboard, nil
}

// GetVersion returns the version of a builtin dashboard by name
// Returns empty string if not found
func (s *BinDashboardsStore) GetVersion(ctx context.Context, name string) string {
	dashboard, err := s.Get(ctx, name)
	if err != nil {
		return ""
	}
	return dashboard.Version
}

// GetAllVersions returns a map of builtin dashboard names to their versions
func (s *BinDashboardsStore) GetAllVersions(ctx context.Context) map[string]string {
	versions := make(map[string]string)
	dashboards, err := s.All(ctx)
	if err != nil {
		return versions
	}
	for _, d := range dashboards {
		versions[d.Name] = d.Version
	}
	return versions
}

// BinAlertTemplatesStore loads alert templates from the JSON files under
// backend/builtin/alerts/, embedded via go-bindata. Read-only.
//
// The parsed result is memoized on first All()/Get() because embedded assets
// are compile-time immutable. The returned templates are treated as read-only
// by handlers and should not be mutated.
type BinAlertTemplatesStore struct {
	Logger cloudhub.Logger

	once   sync.Once
	cached []cloudhub.AlertTemplate
}

const alertAssetPrefix = "alerts/"

// load parses every embedded alert template exactly once and stores the result.
// Invalid files are logged and skipped so a single bad asset does not break the
// whole list.
func (s *BinAlertTemplatesStore) load() []cloudhub.AlertTemplate {
	s.once.Do(func() {
		names := AssetNames()
		out := make([]cloudhub.AlertTemplate, 0, len(names))
		for _, name := range names {
			if !strings.HasPrefix(name, alertAssetPrefix) || !strings.HasSuffix(name, ".json") {
				continue
			}
			octets, err := Asset(name)
			if err != nil {
				s.Logger.
					WithField("component", "builtin").
					WithField("name", name).
					Error("alert template asset read failed: ", err)
				continue
			}
			var tmpl cloudhub.AlertTemplate
			if err := json.Unmarshal(octets, &tmpl); err != nil {
				s.Logger.
					WithField("component", "builtin").
					WithField("name", name).
					Error("alert template unmarshal failed: ", err)
				continue
			}
			if strings.TrimSpace(tmpl.EmailBody) == "" {
				tmpl.EmailBody = defaultAlertTemplateEmailBody()
			}
			out = append(out, tmpl)
		}
		s.cached = out
	})
	return s.cached
}

func defaultAlertTemplateEmailBody() string {
	return `<!doctype html>
<html>
  <body style='margin:0;background:#f5f7fb;font-family:Arial,sans-serif;color:#1f2937;'>
    <table role='presentation' width='100%' cellpadding='0' cellspacing='0' style='background:#f5f7fb;padding:24px;'>
      <tr>
        <td align='center'>
          <table role='presentation' width='640' cellpadding='0' cellspacing='0' style='width:640px;max-width:100%;background:#ffffff;border:1px solid #d9dee8;border-radius:8px;overflow:hidden;'>
            <tr>
              <td style='background:#111827;color:#ffffff;padding:18px 24px;font-size:18px;font-weight:700;'>CloudHub Alert</td>
            </tr>
            <tr>
              <td style='padding:24px;'>
                <div style='display:inline-block;padding:6px 10px;border-radius:4px;background:#fee2e2;color:#991b1b;font-size:12px;font-weight:700;letter-spacing:0;text-transform:uppercase;'>{{ .Level }}</div>
                <h1 style='margin:16px 0 8px;font-size:20px;line-height:1.35;color:#111827;'>{{ .Message }}</h1>
                <p style='margin:0 0 20px;font-size:13px;line-height:1.5;color:#6b7280;'>CloudHub generated this notification from an alert rule.</p>
                <table role='presentation' width='100%' cellpadding='0' cellspacing='0' style='border-collapse:collapse;font-size:14px;'>
                  <tr><td style='padding:10px 0;border-top:1px solid #e5e7eb;color:#6b7280;width:140px;'>Host</td><td style='padding:10px 0;border-top:1px solid #e5e7eb;color:#111827;font-weight:600;'>{{ index .Tags "host" }}</td></tr>
                  <tr><td style='padding:10px 0;border-top:1px solid #e5e7eb;color:#6b7280;'>Level</td><td style='padding:10px 0;border-top:1px solid #e5e7eb;color:#111827;font-weight:600;'>{{ .Level }}</td></tr>
                  <tr><td style='padding:10px 0;border-top:1px solid #e5e7eb;color:#6b7280;'>Time</td><td style='padding:10px 0;border-top:1px solid #e5e7eb;color:#111827;'>{{ .Time }}</td></tr>
                  <tr><td style='padding:10px 0;border-top:1px solid #e5e7eb;color:#6b7280;'>Alert ID</td><td style='padding:10px 0;border-top:1px solid #e5e7eb;color:#111827;'>{{ .ID }}</td></tr>
                </table>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>`
}

// All returns every embedded alert template. The result is served from the
// in-memory cache after the first call.
func (s *BinAlertTemplatesStore) All(ctx context.Context) ([]cloudhub.AlertTemplate, error) {
	return s.load(), nil
}

// Get retrieves a single template by ID. Returns ErrAlertTemplateNotFound when
// no embedded asset matches.
func (s *BinAlertTemplatesStore) Get(ctx context.Context, id string) (cloudhub.AlertTemplate, error) {
	for _, t := range s.load() {
		if t.ID == id {
			return t, nil
		}
	}
	return cloudhub.AlertTemplate{}, cloudhub.ErrAlertTemplateNotFound
}
