package builtin

import (
	"context"
	"encoding/json"
	"strings"

	cloudhub "github.com/snetsystems/cloudhub/backend"
)

//go:generate go-bindata -o bin_gen.go -ignore README|.md|go -pkg builtin ./dashboards

// BinDashboardsStore represents a builtin dashboard store using data generated by go-bindata
type BinDashboardsStore struct {
	Logger cloudhub.Logger
}

// All returns the set of all builtin dashboards
func (s *BinDashboardsStore) All(ctx context.Context) ([]cloudhub.Dashboard, error) {
	names := AssetNames()
	var dashboards []cloudhub.Dashboard

	for _, name := range names {
		// Skip non-JSON files
		if !strings.HasSuffix(name, ".json") {
			continue
		}

		octets, err := Asset(name)
		if err != nil {
			s.Logger.
				WithField("component", "builtin").
				WithField("name", name).
				Error("Invalid Dashboard: ", err)
			continue // Skip invalid files instead of failing completely
		}

		var dashboard cloudhub.Dashboard
		if err = json.Unmarshal(octets, &dashboard); err != nil {
			s.Logger.
				WithField("component", "builtin").
				WithField("name", name).
				Error("Unable to read dashboard:", err)
			continue // Skip invalid files instead of failing completely
		}

		// Ensure type is set to "builtin"
		if dashboard.Type == "" {
			dashboard.Type = "builtin"
		}

		dashboards = append(dashboards, dashboard)
	}

	return dashboards, nil
}

// Get retrieves a builtin dashboard by name
// Name should match the dashboard's Name field (e.g., "Host Page")
func (s *BinDashboardsStore) Get(ctx context.Context, name string) (cloudhub.Dashboard, error) {
	dashboards, err := s.All(ctx)
	if err != nil {
		s.Logger.
			WithField("component", "builtin").
			WithField("name", name).
			Error("Invalid Dashboard: ", err)
		return cloudhub.Dashboard{}, cloudhub.ErrDashboardInvalid
	}

	for _, dashboard := range dashboards {
		if dashboard.Name == name {
			return dashboard, nil
		}
	}

	s.Logger.
		WithField("component", "builtin").
		WithField("name", name).
		Error("Dashboard not found")
	return cloudhub.Dashboard{}, cloudhub.ErrDashboardNotFound
}

// GetByFileName retrieves a builtin dashboard by its JSON file name (without extension)
// e.g., "hostpage" for "hostpage.json"
func (s *BinDashboardsStore) GetByFileName(ctx context.Context, fileName string) (cloudhub.Dashboard, error) {
	// Ensure fileName doesn't have .json extension
	fileName = strings.TrimSuffix(fileName, ".json")

	assetName := "dashboards/" + fileName + ".json"
	octets, err := Asset(assetName)
	if err != nil {
		s.Logger.
			WithField("component", "builtin").
			WithField("name", fileName).
			Error("Dashboard file not found: ", err)
		return cloudhub.Dashboard{}, cloudhub.ErrDashboardNotFound
	}

	var dashboard cloudhub.Dashboard
	if err = json.Unmarshal(octets, &dashboard); err != nil {
		s.Logger.
			WithField("component", "builtin").
			WithField("name", fileName).
			Error("Unable to read dashboard:", err)
		return cloudhub.Dashboard{}, cloudhub.ErrDashboardInvalid
	}

	// Ensure type is set to "builtin"
	if dashboard.Type == "" {
		dashboard.Type = "builtin"
	}

	return dashboard, nil
}
