// Code generated by protoc-gen-gogo. DO NOT EDIT.
// Above sentence is for ignoring about the comment warning by golint.
// So, you can treat as meanless and this is writable.
package bolt

import (
	"log"
	"strings"

	"github.com/boltdb/bolt"
	"github.com/gogo/protobuf/proto"
)

// changeIntervalToDuration
// Before, we supported queries that included `GROUP BY :interval:`
// After, we only support queries with `GROUP BY time(:interval:)`
// thereby allowing non_negative_derivative(_____, :interval)
var changeIntervalToDuration = Migration{
	ID:   "59b0cda4fc7909ff84ee5c4f9cb4b655b6a26620",
	Up:   up,
	Down: down,
}

func updateDashboard(board *Dashboard) {
	for _, cell := range board.Cells {
		for _, query := range cell.Queries {
			query.Command = strings.Replace(query.Command, ":interval:", "time(:interval:)", -1)
		}
	}
}

var up = func(db *bolt.DB) error {
	// For each dashboard
	err := db.Update(func(tx *bolt.Tx) error {
		bucket := tx.Bucket(dashboardBucket)
		err := bucket.ForEach(func(id, data []byte) error {
			board := &Dashboard{}

			err := proto.Unmarshal(data, board)
			if err != nil {
				log.Fatal("unmarshaling error: ", err)
			}

			// Migrate the dashboard
			updateDashboard(board)

			data, err = proto.Marshal(board)
			if err != nil {
				log.Fatal("marshaling error: ", err)
			}

			err = bucket.Put(id, data)
			if err != nil {
				log.Fatal("error updating dashboard: ", err)
			}

			return nil
		})

		if err != nil {
			log.Fatal("error updating dashboards: ", err)
		}

		return nil
	})

	if err != nil {
		return err
	}

	return nil
}

var down = func(db *bolt.DB) error {
	return nil
}

/*
	Import protobuf types and bucket names that are pertinent to this migration.
	This isolates the migration from the codebase, and prevents a future change
	to a type definition from invalidating the migration functions.
*/
var dashboardBucket = []byte("Dashboard")

// DO NOT EDIT from here.
// You need to copy from internal/internal.pb.go, but except "func init()"
type Source struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=Type,proto3" json:"Type,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=Username,proto3" json:"Username,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=Password,proto3" json:"Password,omitempty"`
	URL                  string   `protobuf:"bytes,6,opt,name=URL,proto3" json:"URL,omitempty"`
	Default              bool     `protobuf:"varint,7,opt,name=Default,proto3" json:"Default,omitempty"`
	Telegraf             string   `protobuf:"bytes,8,opt,name=Telegraf,proto3" json:"Telegraf,omitempty"`
	InsecureSkipVerify   bool     `protobuf:"varint,9,opt,name=InsecureSkipVerify,proto3" json:"InsecureSkipVerify,omitempty"`
	MetaURL              string   `protobuf:"bytes,10,opt,name=MetaURL,proto3" json:"MetaURL,omitempty"`
	SharedSecret         string   `protobuf:"bytes,11,opt,name=SharedSecret,proto3" json:"SharedSecret,omitempty"`
	Organization         string   `protobuf:"bytes,12,opt,name=Organization,proto3" json:"Organization,omitempty"`
	Role                 string   `protobuf:"bytes,13,opt,name=Role,proto3" json:"Role,omitempty"`
	DefaultRP            string   `protobuf:"bytes,14,opt,name=DefaultRP,proto3" json:"DefaultRP,omitempty"`
	Version              string   `protobuf:"bytes,15,opt,name=Version,proto3" json:"Version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Source) Reset()         { *m = Source{} }
func (m *Source) String() string { return proto.CompactTextString(m) }
func (*Source) ProtoMessage()    {}
func (*Source) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{0}
}
func (m *Source) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Source.Unmarshal(m, b)
}
func (m *Source) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Source.Marshal(b, m, deterministic)
}
func (m *Source) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Source.Merge(m, src)
}
func (m *Source) XXX_Size() int {
	return xxx_messageInfo_Source.Size(m)
}
func (m *Source) XXX_DiscardUnknown() {
	xxx_messageInfo_Source.DiscardUnknown(m)
}

var xxx_messageInfo_Source proto.InternalMessageInfo

func (m *Source) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Source) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Source) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Source) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Source) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Source) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *Source) GetDefault() bool {
	if m != nil {
		return m.Default
	}
	return false
}

func (m *Source) GetTelegraf() string {
	if m != nil {
		return m.Telegraf
	}
	return ""
}

func (m *Source) GetInsecureSkipVerify() bool {
	if m != nil {
		return m.InsecureSkipVerify
	}
	return false
}

func (m *Source) GetMetaURL() string {
	if m != nil {
		return m.MetaURL
	}
	return ""
}

func (m *Source) GetSharedSecret() string {
	if m != nil {
		return m.SharedSecret
	}
	return ""
}

func (m *Source) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *Source) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *Source) GetDefaultRP() string {
	if m != nil {
		return m.DefaultRP
	}
	return ""
}

func (m *Source) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type Dashboard struct {
	ID                   int64            `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string           `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Cells                []*DashboardCell `protobuf:"bytes,3,rep,name=cells,proto3" json:"cells,omitempty"`
	Templates            []*Template      `protobuf:"bytes,4,rep,name=templates,proto3" json:"templates,omitempty"`
	Organization         string           `protobuf:"bytes,5,opt,name=Organization,proto3" json:"Organization,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Dashboard) Reset()         { *m = Dashboard{} }
func (m *Dashboard) String() string { return proto.CompactTextString(m) }
func (*Dashboard) ProtoMessage()    {}
func (*Dashboard) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{1}
}
func (m *Dashboard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dashboard.Unmarshal(m, b)
}
func (m *Dashboard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dashboard.Marshal(b, m, deterministic)
}
func (m *Dashboard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dashboard.Merge(m, src)
}
func (m *Dashboard) XXX_Size() int {
	return xxx_messageInfo_Dashboard.Size(m)
}
func (m *Dashboard) XXX_DiscardUnknown() {
	xxx_messageInfo_Dashboard.DiscardUnknown(m)
}

var xxx_messageInfo_Dashboard proto.InternalMessageInfo

func (m *Dashboard) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Dashboard) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Dashboard) GetCells() []*DashboardCell {
	if m != nil {
		return m.Cells
	}
	return nil
}

func (m *Dashboard) GetTemplates() []*Template {
	if m != nil {
		return m.Templates
	}
	return nil
}

func (m *Dashboard) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

type DashboardCell struct {
	X                    int32             `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32             `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	W                    int32             `protobuf:"varint,3,opt,name=w,proto3" json:"w,omitempty"`
	H                    int32             `protobuf:"varint,4,opt,name=h,proto3" json:"h,omitempty"`
	Queries              []*Query          `protobuf:"bytes,5,rep,name=queries,proto3" json:"queries,omitempty"`
	Name                 string            `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string            `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	ID                   string            `protobuf:"bytes,8,opt,name=ID,proto3" json:"ID,omitempty"`
	Axes                 map[string]*Axis  `protobuf:"bytes,9,rep,name=axes,proto3" json:"axes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Colors               []*Color          `protobuf:"bytes,10,rep,name=colors,proto3" json:"colors,omitempty"`
	Legend               *Legend           `protobuf:"bytes,11,opt,name=legend,proto3" json:"legend,omitempty"`
	TableOptions         *TableOptions     `protobuf:"bytes,12,opt,name=tableOptions,proto3" json:"tableOptions,omitempty"`
	FieldOptions         []*RenamableField `protobuf:"bytes,13,rep,name=fieldOptions,proto3" json:"fieldOptions,omitempty"`
	TimeFormat           string            `protobuf:"bytes,14,opt,name=timeFormat,proto3" json:"timeFormat,omitempty"`
	DecimalPlaces        *DecimalPlaces    `protobuf:"bytes,15,opt,name=decimalPlaces,proto3" json:"decimalPlaces,omitempty"`
	Note                 string            `protobuf:"bytes,16,opt,name=note,proto3" json:"note,omitempty"`
	NoteVisibility       string            `protobuf:"bytes,17,opt,name=noteVisibility,proto3" json:"noteVisibility,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DashboardCell) Reset()         { *m = DashboardCell{} }
func (m *DashboardCell) String() string { return proto.CompactTextString(m) }
func (*DashboardCell) ProtoMessage()    {}
func (*DashboardCell) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{2}
}
func (m *DashboardCell) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DashboardCell.Unmarshal(m, b)
}
func (m *DashboardCell) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DashboardCell.Marshal(b, m, deterministic)
}
func (m *DashboardCell) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DashboardCell.Merge(m, src)
}
func (m *DashboardCell) XXX_Size() int {
	return xxx_messageInfo_DashboardCell.Size(m)
}
func (m *DashboardCell) XXX_DiscardUnknown() {
	xxx_messageInfo_DashboardCell.DiscardUnknown(m)
}

var xxx_messageInfo_DashboardCell proto.InternalMessageInfo

func (m *DashboardCell) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *DashboardCell) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *DashboardCell) GetW() int32 {
	if m != nil {
		return m.W
	}
	return 0
}

func (m *DashboardCell) GetH() int32 {
	if m != nil {
		return m.H
	}
	return 0
}

func (m *DashboardCell) GetQueries() []*Query {
	if m != nil {
		return m.Queries
	}
	return nil
}

func (m *DashboardCell) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DashboardCell) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *DashboardCell) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *DashboardCell) GetAxes() map[string]*Axis {
	if m != nil {
		return m.Axes
	}
	return nil
}

func (m *DashboardCell) GetColors() []*Color {
	if m != nil {
		return m.Colors
	}
	return nil
}

func (m *DashboardCell) GetLegend() *Legend {
	if m != nil {
		return m.Legend
	}
	return nil
}

func (m *DashboardCell) GetTableOptions() *TableOptions {
	if m != nil {
		return m.TableOptions
	}
	return nil
}

func (m *DashboardCell) GetFieldOptions() []*RenamableField {
	if m != nil {
		return m.FieldOptions
	}
	return nil
}

func (m *DashboardCell) GetTimeFormat() string {
	if m != nil {
		return m.TimeFormat
	}
	return ""
}

func (m *DashboardCell) GetDecimalPlaces() *DecimalPlaces {
	if m != nil {
		return m.DecimalPlaces
	}
	return nil
}

func (m *DashboardCell) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *DashboardCell) GetNoteVisibility() string {
	if m != nil {
		return m.NoteVisibility
	}
	return ""
}

type DecimalPlaces struct {
	IsEnforced           bool     `protobuf:"varint,1,opt,name=isEnforced,proto3" json:"isEnforced,omitempty"`
	Digits               int32    `protobuf:"varint,2,opt,name=digits,proto3" json:"digits,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecimalPlaces) Reset()         { *m = DecimalPlaces{} }
func (m *DecimalPlaces) String() string { return proto.CompactTextString(m) }
func (*DecimalPlaces) ProtoMessage()    {}
func (*DecimalPlaces) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{3}
}
func (m *DecimalPlaces) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecimalPlaces.Unmarshal(m, b)
}
func (m *DecimalPlaces) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecimalPlaces.Marshal(b, m, deterministic)
}
func (m *DecimalPlaces) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecimalPlaces.Merge(m, src)
}
func (m *DecimalPlaces) XXX_Size() int {
	return xxx_messageInfo_DecimalPlaces.Size(m)
}
func (m *DecimalPlaces) XXX_DiscardUnknown() {
	xxx_messageInfo_DecimalPlaces.DiscardUnknown(m)
}

var xxx_messageInfo_DecimalPlaces proto.InternalMessageInfo

func (m *DecimalPlaces) GetIsEnforced() bool {
	if m != nil {
		return m.IsEnforced
	}
	return false
}

func (m *DecimalPlaces) GetDigits() int32 {
	if m != nil {
		return m.Digits
	}
	return 0
}

type TableOptions struct {
	VerticalTimeAxis     bool            `protobuf:"varint,2,opt,name=verticalTimeAxis,proto3" json:"verticalTimeAxis,omitempty"`
	SortBy               *RenamableField `protobuf:"bytes,3,opt,name=sortBy,proto3" json:"sortBy,omitempty"`
	Wrapping             string          `protobuf:"bytes,4,opt,name=wrapping,proto3" json:"wrapping,omitempty"`
	FixFirstColumn       bool            `protobuf:"varint,6,opt,name=fixFirstColumn,proto3" json:"fixFirstColumn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TableOptions) Reset()         { *m = TableOptions{} }
func (m *TableOptions) String() string { return proto.CompactTextString(m) }
func (*TableOptions) ProtoMessage()    {}
func (*TableOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{4}
}
func (m *TableOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableOptions.Unmarshal(m, b)
}
func (m *TableOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableOptions.Marshal(b, m, deterministic)
}
func (m *TableOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableOptions.Merge(m, src)
}
func (m *TableOptions) XXX_Size() int {
	return xxx_messageInfo_TableOptions.Size(m)
}
func (m *TableOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_TableOptions.DiscardUnknown(m)
}

var xxx_messageInfo_TableOptions proto.InternalMessageInfo

func (m *TableOptions) GetVerticalTimeAxis() bool {
	if m != nil {
		return m.VerticalTimeAxis
	}
	return false
}

func (m *TableOptions) GetSortBy() *RenamableField {
	if m != nil {
		return m.SortBy
	}
	return nil
}

func (m *TableOptions) GetWrapping() string {
	if m != nil {
		return m.Wrapping
	}
	return ""
}

func (m *TableOptions) GetFixFirstColumn() bool {
	if m != nil {
		return m.FixFirstColumn
	}
	return false
}

type RenamableField struct {
	InternalName         string   `protobuf:"bytes,1,opt,name=internalName,proto3" json:"internalName,omitempty"`
	DisplayName          string   `protobuf:"bytes,2,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Visible              bool     `protobuf:"varint,3,opt,name=visible,proto3" json:"visible,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenamableField) Reset()         { *m = RenamableField{} }
func (m *RenamableField) String() string { return proto.CompactTextString(m) }
func (*RenamableField) ProtoMessage()    {}
func (*RenamableField) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{5}
}
func (m *RenamableField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenamableField.Unmarshal(m, b)
}
func (m *RenamableField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenamableField.Marshal(b, m, deterministic)
}
func (m *RenamableField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenamableField.Merge(m, src)
}
func (m *RenamableField) XXX_Size() int {
	return xxx_messageInfo_RenamableField.Size(m)
}
func (m *RenamableField) XXX_DiscardUnknown() {
	xxx_messageInfo_RenamableField.DiscardUnknown(m)
}

var xxx_messageInfo_RenamableField proto.InternalMessageInfo

func (m *RenamableField) GetInternalName() string {
	if m != nil {
		return m.InternalName
	}
	return ""
}

func (m *RenamableField) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *RenamableField) GetVisible() bool {
	if m != nil {
		return m.Visible
	}
	return false
}

type Color struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Hex                  string   `protobuf:"bytes,3,opt,name=Hex,proto3" json:"Hex,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	Value                string   `protobuf:"bytes,5,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Color) Reset()         { *m = Color{} }
func (m *Color) String() string { return proto.CompactTextString(m) }
func (*Color) ProtoMessage()    {}
func (*Color) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{6}
}
func (m *Color) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Color.Unmarshal(m, b)
}
func (m *Color) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Color.Marshal(b, m, deterministic)
}
func (m *Color) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Color.Merge(m, src)
}
func (m *Color) XXX_Size() int {
	return xxx_messageInfo_Color.Size(m)
}
func (m *Color) XXX_DiscardUnknown() {
	xxx_messageInfo_Color.DiscardUnknown(m)
}

var xxx_messageInfo_Color proto.InternalMessageInfo

func (m *Color) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Color) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Color) GetHex() string {
	if m != nil {
		return m.Hex
	}
	return ""
}

func (m *Color) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Color) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Legend struct {
	Type                 string   `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Orientation          string   `protobuf:"bytes,2,opt,name=Orientation,proto3" json:"Orientation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Legend) Reset()         { *m = Legend{} }
func (m *Legend) String() string { return proto.CompactTextString(m) }
func (*Legend) ProtoMessage()    {}
func (*Legend) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{7}
}
func (m *Legend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Legend.Unmarshal(m, b)
}
func (m *Legend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Legend.Marshal(b, m, deterministic)
}
func (m *Legend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Legend.Merge(m, src)
}
func (m *Legend) XXX_Size() int {
	return xxx_messageInfo_Legend.Size(m)
}
func (m *Legend) XXX_DiscardUnknown() {
	xxx_messageInfo_Legend.DiscardUnknown(m)
}

var xxx_messageInfo_Legend proto.InternalMessageInfo

func (m *Legend) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Legend) GetOrientation() string {
	if m != nil {
		return m.Orientation
	}
	return ""
}

type Axis struct {
	LegacyBounds         []int64  `protobuf:"varint,1,rep,packed,name=legacyBounds,proto3" json:"legacyBounds,omitempty"`
	Bounds               []string `protobuf:"bytes,2,rep,name=bounds,proto3" json:"bounds,omitempty"`
	Label                string   `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Prefix               string   `protobuf:"bytes,4,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Suffix               string   `protobuf:"bytes,5,opt,name=suffix,proto3" json:"suffix,omitempty"`
	Base                 string   `protobuf:"bytes,6,opt,name=base,proto3" json:"base,omitempty"`
	Scale                string   `protobuf:"bytes,7,opt,name=scale,proto3" json:"scale,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Axis) Reset()         { *m = Axis{} }
func (m *Axis) String() string { return proto.CompactTextString(m) }
func (*Axis) ProtoMessage()    {}
func (*Axis) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{8}
}
func (m *Axis) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Axis.Unmarshal(m, b)
}
func (m *Axis) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Axis.Marshal(b, m, deterministic)
}
func (m *Axis) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Axis.Merge(m, src)
}
func (m *Axis) XXX_Size() int {
	return xxx_messageInfo_Axis.Size(m)
}
func (m *Axis) XXX_DiscardUnknown() {
	xxx_messageInfo_Axis.DiscardUnknown(m)
}

var xxx_messageInfo_Axis proto.InternalMessageInfo

func (m *Axis) GetLegacyBounds() []int64 {
	if m != nil {
		return m.LegacyBounds
	}
	return nil
}

func (m *Axis) GetBounds() []string {
	if m != nil {
		return m.Bounds
	}
	return nil
}

func (m *Axis) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Axis) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *Axis) GetSuffix() string {
	if m != nil {
		return m.Suffix
	}
	return ""
}

func (m *Axis) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

func (m *Axis) GetScale() string {
	if m != nil {
		return m.Scale
	}
	return ""
}

type Template struct {
	ID                   string           `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	TempVar              string           `protobuf:"bytes,2,opt,name=temp_var,json=tempVar,proto3" json:"temp_var,omitempty"`
	Values               []*TemplateValue `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	Type                 string           `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Label                string           `protobuf:"bytes,5,opt,name=label,proto3" json:"label,omitempty"`
	Query                *TemplateQuery   `protobuf:"bytes,6,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Template) Reset()         { *m = Template{} }
func (m *Template) String() string { return proto.CompactTextString(m) }
func (*Template) ProtoMessage()    {}
func (*Template) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{9}
}
func (m *Template) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Template.Unmarshal(m, b)
}
func (m *Template) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Template.Marshal(b, m, deterministic)
}
func (m *Template) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Template.Merge(m, src)
}
func (m *Template) XXX_Size() int {
	return xxx_messageInfo_Template.Size(m)
}
func (m *Template) XXX_DiscardUnknown() {
	xxx_messageInfo_Template.DiscardUnknown(m)
}

var xxx_messageInfo_Template proto.InternalMessageInfo

func (m *Template) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Template) GetTempVar() string {
	if m != nil {
		return m.TempVar
	}
	return ""
}

func (m *Template) GetValues() []*TemplateValue {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *Template) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Template) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Template) GetQuery() *TemplateQuery {
	if m != nil {
		return m.Query
	}
	return nil
}

type TemplateValue struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Selected             bool     `protobuf:"varint,3,opt,name=selected,proto3" json:"selected,omitempty"`
	Key                  string   `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TemplateValue) Reset()         { *m = TemplateValue{} }
func (m *TemplateValue) String() string { return proto.CompactTextString(m) }
func (*TemplateValue) ProtoMessage()    {}
func (*TemplateValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{10}
}
func (m *TemplateValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateValue.Unmarshal(m, b)
}
func (m *TemplateValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateValue.Marshal(b, m, deterministic)
}
func (m *TemplateValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateValue.Merge(m, src)
}
func (m *TemplateValue) XXX_Size() int {
	return xxx_messageInfo_TemplateValue.Size(m)
}
func (m *TemplateValue) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateValue.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateValue proto.InternalMessageInfo

func (m *TemplateValue) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TemplateValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *TemplateValue) GetSelected() bool {
	if m != nil {
		return m.Selected
	}
	return false
}

func (m *TemplateValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type TemplateQuery struct {
	Command              string   `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Db                   string   `protobuf:"bytes,2,opt,name=db,proto3" json:"db,omitempty"`
	Rp                   string   `protobuf:"bytes,3,opt,name=rp,proto3" json:"rp,omitempty"`
	Measurement          string   `protobuf:"bytes,4,opt,name=measurement,proto3" json:"measurement,omitempty"`
	TagKey               string   `protobuf:"bytes,5,opt,name=tag_key,json=tagKey,proto3" json:"tag_key,omitempty"`
	FieldKey             string   `protobuf:"bytes,6,opt,name=field_key,json=fieldKey,proto3" json:"field_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TemplateQuery) Reset()         { *m = TemplateQuery{} }
func (m *TemplateQuery) String() string { return proto.CompactTextString(m) }
func (*TemplateQuery) ProtoMessage()    {}
func (*TemplateQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{11}
}
func (m *TemplateQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateQuery.Unmarshal(m, b)
}
func (m *TemplateQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateQuery.Marshal(b, m, deterministic)
}
func (m *TemplateQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateQuery.Merge(m, src)
}
func (m *TemplateQuery) XXX_Size() int {
	return xxx_messageInfo_TemplateQuery.Size(m)
}
func (m *TemplateQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateQuery.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateQuery proto.InternalMessageInfo

func (m *TemplateQuery) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *TemplateQuery) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

func (m *TemplateQuery) GetRp() string {
	if m != nil {
		return m.Rp
	}
	return ""
}

func (m *TemplateQuery) GetMeasurement() string {
	if m != nil {
		return m.Measurement
	}
	return ""
}

func (m *TemplateQuery) GetTagKey() string {
	if m != nil {
		return m.TagKey
	}
	return ""
}

func (m *TemplateQuery) GetFieldKey() string {
	if m != nil {
		return m.FieldKey
	}
	return ""
}

type Server struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=Username,proto3" json:"Username,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	URL                  string   `protobuf:"bytes,5,opt,name=URL,proto3" json:"URL,omitempty"`
	SrcID                int64    `protobuf:"varint,6,opt,name=SrcID,proto3" json:"SrcID,omitempty"`
	Active               bool     `protobuf:"varint,7,opt,name=Active,proto3" json:"Active,omitempty"`
	Organization         string   `protobuf:"bytes,8,opt,name=Organization,proto3" json:"Organization,omitempty"`
	InsecureSkipVerify   bool     `protobuf:"varint,9,opt,name=InsecureSkipVerify,proto3" json:"InsecureSkipVerify,omitempty"`
	Type                 string   `protobuf:"bytes,10,opt,name=Type,proto3" json:"Type,omitempty"`
	MetadataJSON         string   `protobuf:"bytes,11,opt,name=MetadataJSON,proto3" json:"MetadataJSON,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Server) Reset()         { *m = Server{} }
func (m *Server) String() string { return proto.CompactTextString(m) }
func (*Server) ProtoMessage()    {}
func (*Server) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{12}
}
func (m *Server) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Server.Unmarshal(m, b)
}
func (m *Server) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Server.Marshal(b, m, deterministic)
}
func (m *Server) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Server.Merge(m, src)
}
func (m *Server) XXX_Size() int {
	return xxx_messageInfo_Server.Size(m)
}
func (m *Server) XXX_DiscardUnknown() {
	xxx_messageInfo_Server.DiscardUnknown(m)
}

var xxx_messageInfo_Server proto.InternalMessageInfo

func (m *Server) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Server) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Server) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Server) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Server) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func (m *Server) GetSrcID() int64 {
	if m != nil {
		return m.SrcID
	}
	return 0
}

func (m *Server) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Server) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *Server) GetInsecureSkipVerify() bool {
	if m != nil {
		return m.InsecureSkipVerify
	}
	return false
}

func (m *Server) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Server) GetMetadataJSON() string {
	if m != nil {
		return m.MetadataJSON
	}
	return ""
}

type Layout struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Application          string   `protobuf:"bytes,2,opt,name=Application,proto3" json:"Application,omitempty"`
	Measurement          string   `protobuf:"bytes,3,opt,name=Measurement,proto3" json:"Measurement,omitempty"`
	Cells                []*Cell  `protobuf:"bytes,4,rep,name=Cells,proto3" json:"Cells,omitempty"`
	Autoflow             bool     `protobuf:"varint,5,opt,name=Autoflow,proto3" json:"Autoflow,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Layout) Reset()         { *m = Layout{} }
func (m *Layout) String() string { return proto.CompactTextString(m) }
func (*Layout) ProtoMessage()    {}
func (*Layout) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{13}
}
func (m *Layout) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Layout.Unmarshal(m, b)
}
func (m *Layout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Layout.Marshal(b, m, deterministic)
}
func (m *Layout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Layout.Merge(m, src)
}
func (m *Layout) XXX_Size() int {
	return xxx_messageInfo_Layout.Size(m)
}
func (m *Layout) XXX_DiscardUnknown() {
	xxx_messageInfo_Layout.DiscardUnknown(m)
}

var xxx_messageInfo_Layout proto.InternalMessageInfo

func (m *Layout) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Layout) GetApplication() string {
	if m != nil {
		return m.Application
	}
	return ""
}

func (m *Layout) GetMeasurement() string {
	if m != nil {
		return m.Measurement
	}
	return ""
}

func (m *Layout) GetCells() []*Cell {
	if m != nil {
		return m.Cells
	}
	return nil
}

func (m *Layout) GetAutoflow() bool {
	if m != nil {
		return m.Autoflow
	}
	return false
}

type Cell struct {
	X                    int32            `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32            `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	W                    int32            `protobuf:"varint,3,opt,name=w,proto3" json:"w,omitempty"`
	H                    int32            `protobuf:"varint,4,opt,name=h,proto3" json:"h,omitempty"`
	Queries              []*Query         `protobuf:"bytes,5,rep,name=queries,proto3" json:"queries,omitempty"`
	I                    string           `protobuf:"bytes,6,opt,name=i,proto3" json:"i,omitempty"`
	Name                 string           `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Yranges              []int64          `protobuf:"varint,8,rep,packed,name=yranges,proto3" json:"yranges,omitempty"`
	Ylabels              []string         `protobuf:"bytes,9,rep,name=ylabels,proto3" json:"ylabels,omitempty"`
	Type                 string           `protobuf:"bytes,10,opt,name=type,proto3" json:"type,omitempty"`
	Axes                 map[string]*Axis `protobuf:"bytes,11,rep,name=axes,proto3" json:"axes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Cell) Reset()         { *m = Cell{} }
func (m *Cell) String() string { return proto.CompactTextString(m) }
func (*Cell) ProtoMessage()    {}
func (*Cell) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{14}
}
func (m *Cell) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cell.Unmarshal(m, b)
}
func (m *Cell) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cell.Marshal(b, m, deterministic)
}
func (m *Cell) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cell.Merge(m, src)
}
func (m *Cell) XXX_Size() int {
	return xxx_messageInfo_Cell.Size(m)
}
func (m *Cell) XXX_DiscardUnknown() {
	xxx_messageInfo_Cell.DiscardUnknown(m)
}

var xxx_messageInfo_Cell proto.InternalMessageInfo

func (m *Cell) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Cell) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Cell) GetW() int32 {
	if m != nil {
		return m.W
	}
	return 0
}

func (m *Cell) GetH() int32 {
	if m != nil {
		return m.H
	}
	return 0
}

func (m *Cell) GetQueries() []*Query {
	if m != nil {
		return m.Queries
	}
	return nil
}

func (m *Cell) GetI() string {
	if m != nil {
		return m.I
	}
	return ""
}

func (m *Cell) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Cell) GetYranges() []int64 {
	if m != nil {
		return m.Yranges
	}
	return nil
}

func (m *Cell) GetYlabels() []string {
	if m != nil {
		return m.Ylabels
	}
	return nil
}

func (m *Cell) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Cell) GetAxes() map[string]*Axis {
	if m != nil {
		return m.Axes
	}
	return nil
}

type Query struct {
	Command              string       `protobuf:"bytes,1,opt,name=Command,proto3" json:"Command,omitempty"`
	DB                   string       `protobuf:"bytes,2,opt,name=DB,proto3" json:"DB,omitempty"`
	RP                   string       `protobuf:"bytes,3,opt,name=RP,proto3" json:"RP,omitempty"`
	GroupBys             []string     `protobuf:"bytes,4,rep,name=GroupBys,proto3" json:"GroupBys,omitempty"`
	Wheres               []string     `protobuf:"bytes,5,rep,name=Wheres,proto3" json:"Wheres,omitempty"`
	Label                string       `protobuf:"bytes,6,opt,name=Label,proto3" json:"Label,omitempty"`
	Range                *Range       `protobuf:"bytes,7,opt,name=Range,proto3" json:"Range,omitempty"`
	Source               string       `protobuf:"bytes,8,opt,name=Source,proto3" json:"Source,omitempty"`
	Shifts               []*TimeShift `protobuf:"bytes,9,rep,name=Shifts,proto3" json:"Shifts,omitempty"`
	Type                 string       `protobuf:"bytes,10,opt,name=Type,proto3" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{15}
}
func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *Query) GetDB() string {
	if m != nil {
		return m.DB
	}
	return ""
}

func (m *Query) GetRP() string {
	if m != nil {
		return m.RP
	}
	return ""
}

func (m *Query) GetGroupBys() []string {
	if m != nil {
		return m.GroupBys
	}
	return nil
}

func (m *Query) GetWheres() []string {
	if m != nil {
		return m.Wheres
	}
	return nil
}

func (m *Query) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Query) GetRange() *Range {
	if m != nil {
		return m.Range
	}
	return nil
}

func (m *Query) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Query) GetShifts() []*TimeShift {
	if m != nil {
		return m.Shifts
	}
	return nil
}

func (m *Query) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type TimeShift struct {
	Label                string   `protobuf:"bytes,1,opt,name=Label,proto3" json:"Label,omitempty"`
	Unit                 string   `protobuf:"bytes,2,opt,name=Unit,proto3" json:"Unit,omitempty"`
	Quantity             string   `protobuf:"bytes,3,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeShift) Reset()         { *m = TimeShift{} }
func (m *TimeShift) String() string { return proto.CompactTextString(m) }
func (*TimeShift) ProtoMessage()    {}
func (*TimeShift) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{16}
}
func (m *TimeShift) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeShift.Unmarshal(m, b)
}
func (m *TimeShift) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeShift.Marshal(b, m, deterministic)
}
func (m *TimeShift) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeShift.Merge(m, src)
}
func (m *TimeShift) XXX_Size() int {
	return xxx_messageInfo_TimeShift.Size(m)
}
func (m *TimeShift) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeShift.DiscardUnknown(m)
}

var xxx_messageInfo_TimeShift proto.InternalMessageInfo

func (m *TimeShift) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *TimeShift) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *TimeShift) GetQuantity() string {
	if m != nil {
		return m.Quantity
	}
	return ""
}

type Range struct {
	Upper                int64    `protobuf:"varint,1,opt,name=Upper,proto3" json:"Upper,omitempty"`
	Lower                int64    `protobuf:"varint,2,opt,name=Lower,proto3" json:"Lower,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Range) Reset()         { *m = Range{} }
func (m *Range) String() string { return proto.CompactTextString(m) }
func (*Range) ProtoMessage()    {}
func (*Range) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{17}
}
func (m *Range) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Range.Unmarshal(m, b)
}
func (m *Range) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Range.Marshal(b, m, deterministic)
}
func (m *Range) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Range.Merge(m, src)
}
func (m *Range) XXX_Size() int {
	return xxx_messageInfo_Range.Size(m)
}
func (m *Range) XXX_DiscardUnknown() {
	xxx_messageInfo_Range.DiscardUnknown(m)
}

var xxx_messageInfo_Range proto.InternalMessageInfo

func (m *Range) GetUpper() int64 {
	if m != nil {
		return m.Upper
	}
	return 0
}

func (m *Range) GetLower() int64 {
	if m != nil {
		return m.Lower
	}
	return 0
}

type AlertRule struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	JSON                 string   `protobuf:"bytes,2,opt,name=JSON,proto3" json:"JSON,omitempty"`
	SrcID                int64    `protobuf:"varint,3,opt,name=SrcID,proto3" json:"SrcID,omitempty"`
	KapaID               int64    `protobuf:"varint,4,opt,name=KapaID,proto3" json:"KapaID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlertRule) Reset()         { *m = AlertRule{} }
func (m *AlertRule) String() string { return proto.CompactTextString(m) }
func (*AlertRule) ProtoMessage()    {}
func (*AlertRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{18}
}
func (m *AlertRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlertRule.Unmarshal(m, b)
}
func (m *AlertRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlertRule.Marshal(b, m, deterministic)
}
func (m *AlertRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlertRule.Merge(m, src)
}
func (m *AlertRule) XXX_Size() int {
	return xxx_messageInfo_AlertRule.Size(m)
}
func (m *AlertRule) XXX_DiscardUnknown() {
	xxx_messageInfo_AlertRule.DiscardUnknown(m)
}

var xxx_messageInfo_AlertRule proto.InternalMessageInfo

func (m *AlertRule) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *AlertRule) GetJSON() string {
	if m != nil {
		return m.JSON
	}
	return ""
}

func (m *AlertRule) GetSrcID() int64 {
	if m != nil {
		return m.SrcID
	}
	return 0
}

func (m *AlertRule) GetKapaID() int64 {
	if m != nil {
		return m.KapaID
	}
	return 0
}

type User struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Provider             string   `protobuf:"bytes,3,opt,name=Provider,proto3" json:"Provider,omitempty"`
	Scheme               string   `protobuf:"bytes,4,opt,name=Scheme,proto3" json:"Scheme,omitempty"`
	Roles                []*Role  `protobuf:"bytes,5,rep,name=Roles,proto3" json:"Roles,omitempty"`
	SuperAdmin           bool     `protobuf:"varint,6,opt,name=SuperAdmin,proto3" json:"SuperAdmin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{19}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *User) GetScheme() string {
	if m != nil {
		return m.Scheme
	}
	return ""
}

func (m *User) GetRoles() []*Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *User) GetSuperAdmin() bool {
	if m != nil {
		return m.SuperAdmin
	}
	return false
}

type Role struct {
	Organization         string   `protobuf:"bytes,1,opt,name=Organization,proto3" json:"Organization,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{20}
}
func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (m *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(m, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *Role) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Mapping struct {
	Provider             string   `protobuf:"bytes,1,opt,name=Provider,proto3" json:"Provider,omitempty"`
	Scheme               string   `protobuf:"bytes,2,opt,name=Scheme,proto3" json:"Scheme,omitempty"`
	ProviderOrganization string   `protobuf:"bytes,3,opt,name=ProviderOrganization,proto3" json:"ProviderOrganization,omitempty"`
	ID                   string   `protobuf:"bytes,4,opt,name=ID,proto3" json:"ID,omitempty"`
	Organization         string   `protobuf:"bytes,5,opt,name=Organization,proto3" json:"Organization,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mapping) Reset()         { *m = Mapping{} }
func (m *Mapping) String() string { return proto.CompactTextString(m) }
func (*Mapping) ProtoMessage()    {}
func (*Mapping) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{21}
}
func (m *Mapping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mapping.Unmarshal(m, b)
}
func (m *Mapping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mapping.Marshal(b, m, deterministic)
}
func (m *Mapping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mapping.Merge(m, src)
}
func (m *Mapping) XXX_Size() int {
	return xxx_messageInfo_Mapping.Size(m)
}
func (m *Mapping) XXX_DiscardUnknown() {
	xxx_messageInfo_Mapping.DiscardUnknown(m)
}

var xxx_messageInfo_Mapping proto.InternalMessageInfo

func (m *Mapping) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *Mapping) GetScheme() string {
	if m != nil {
		return m.Scheme
	}
	return ""
}

func (m *Mapping) GetProviderOrganization() string {
	if m != nil {
		return m.ProviderOrganization
	}
	return ""
}

func (m *Mapping) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Mapping) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

type Organization struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	DefaultRole          string   `protobuf:"bytes,3,opt,name=DefaultRole,proto3" json:"DefaultRole,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Organization) Reset()         { *m = Organization{} }
func (m *Organization) String() string { return proto.CompactTextString(m) }
func (*Organization) ProtoMessage()    {}
func (*Organization) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{22}
}
func (m *Organization) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Organization.Unmarshal(m, b)
}
func (m *Organization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Organization.Marshal(b, m, deterministic)
}
func (m *Organization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Organization.Merge(m, src)
}
func (m *Organization) XXX_Size() int {
	return xxx_messageInfo_Organization.Size(m)
}
func (m *Organization) XXX_DiscardUnknown() {
	xxx_messageInfo_Organization.DiscardUnknown(m)
}

var xxx_messageInfo_Organization proto.InternalMessageInfo

func (m *Organization) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Organization) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Organization) GetDefaultRole() string {
	if m != nil {
		return m.DefaultRole
	}
	return ""
}

type Config struct {
	Auth                 *AuthConfig `protobuf:"bytes,1,opt,name=Auth,proto3" json:"Auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{23}
}
func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetAuth() *AuthConfig {
	if m != nil {
		return m.Auth
	}
	return nil
}

type AuthConfig struct {
	SuperAdminNewUsers   bool     `protobuf:"varint,1,opt,name=SuperAdminNewUsers,proto3" json:"SuperAdminNewUsers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthConfig) Reset()         { *m = AuthConfig{} }
func (m *AuthConfig) String() string { return proto.CompactTextString(m) }
func (*AuthConfig) ProtoMessage()    {}
func (*AuthConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{24}
}
func (m *AuthConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthConfig.Unmarshal(m, b)
}
func (m *AuthConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthConfig.Marshal(b, m, deterministic)
}
func (m *AuthConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthConfig.Merge(m, src)
}
func (m *AuthConfig) XXX_Size() int {
	return xxx_messageInfo_AuthConfig.Size(m)
}
func (m *AuthConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthConfig.DiscardUnknown(m)
}

var xxx_messageInfo_AuthConfig proto.InternalMessageInfo

func (m *AuthConfig) GetSuperAdminNewUsers() bool {
	if m != nil {
		return m.SuperAdminNewUsers
	}
	return false
}

type OrganizationConfig struct {
	OrganizationID       string           `protobuf:"bytes,1,opt,name=OrganizationID,proto3" json:"OrganizationID,omitempty"`
	LogViewer            *LogViewerConfig `protobuf:"bytes,2,opt,name=LogViewer,proto3" json:"LogViewer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *OrganizationConfig) Reset()         { *m = OrganizationConfig{} }
func (m *OrganizationConfig) String() string { return proto.CompactTextString(m) }
func (*OrganizationConfig) ProtoMessage()    {}
func (*OrganizationConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{25}
}
func (m *OrganizationConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrganizationConfig.Unmarshal(m, b)
}
func (m *OrganizationConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrganizationConfig.Marshal(b, m, deterministic)
}
func (m *OrganizationConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrganizationConfig.Merge(m, src)
}
func (m *OrganizationConfig) XXX_Size() int {
	return xxx_messageInfo_OrganizationConfig.Size(m)
}
func (m *OrganizationConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_OrganizationConfig.DiscardUnknown(m)
}

var xxx_messageInfo_OrganizationConfig proto.InternalMessageInfo

func (m *OrganizationConfig) GetOrganizationID() string {
	if m != nil {
		return m.OrganizationID
	}
	return ""
}

func (m *OrganizationConfig) GetLogViewer() *LogViewerConfig {
	if m != nil {
		return m.LogViewer
	}
	return nil
}

type LogViewerConfig struct {
	Columns              []*LogViewerColumn `protobuf:"bytes,1,rep,name=Columns,proto3" json:"Columns,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *LogViewerConfig) Reset()         { *m = LogViewerConfig{} }
func (m *LogViewerConfig) String() string { return proto.CompactTextString(m) }
func (*LogViewerConfig) ProtoMessage()    {}
func (*LogViewerConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{26}
}
func (m *LogViewerConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogViewerConfig.Unmarshal(m, b)
}
func (m *LogViewerConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogViewerConfig.Marshal(b, m, deterministic)
}
func (m *LogViewerConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogViewerConfig.Merge(m, src)
}
func (m *LogViewerConfig) XXX_Size() int {
	return xxx_messageInfo_LogViewerConfig.Size(m)
}
func (m *LogViewerConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_LogViewerConfig.DiscardUnknown(m)
}

var xxx_messageInfo_LogViewerConfig proto.InternalMessageInfo

func (m *LogViewerConfig) GetColumns() []*LogViewerColumn {
	if m != nil {
		return m.Columns
	}
	return nil
}

type LogViewerColumn struct {
	Name                 string            `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Position             int32             `protobuf:"varint,2,opt,name=Position,proto3" json:"Position,omitempty"`
	Encodings            []*ColumnEncoding `protobuf:"bytes,3,rep,name=Encodings,proto3" json:"Encodings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LogViewerColumn) Reset()         { *m = LogViewerColumn{} }
func (m *LogViewerColumn) String() string { return proto.CompactTextString(m) }
func (*LogViewerColumn) ProtoMessage()    {}
func (*LogViewerColumn) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{27}
}
func (m *LogViewerColumn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogViewerColumn.Unmarshal(m, b)
}
func (m *LogViewerColumn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogViewerColumn.Marshal(b, m, deterministic)
}
func (m *LogViewerColumn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogViewerColumn.Merge(m, src)
}
func (m *LogViewerColumn) XXX_Size() int {
	return xxx_messageInfo_LogViewerColumn.Size(m)
}
func (m *LogViewerColumn) XXX_DiscardUnknown() {
	xxx_messageInfo_LogViewerColumn.DiscardUnknown(m)
}

var xxx_messageInfo_LogViewerColumn proto.InternalMessageInfo

func (m *LogViewerColumn) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LogViewerColumn) GetPosition() int32 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *LogViewerColumn) GetEncodings() []*ColumnEncoding {
	if m != nil {
		return m.Encodings
	}
	return nil
}

type ColumnEncoding struct {
	Type                 string   `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ColumnEncoding) Reset()         { *m = ColumnEncoding{} }
func (m *ColumnEncoding) String() string { return proto.CompactTextString(m) }
func (*ColumnEncoding) ProtoMessage()    {}
func (*ColumnEncoding) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{28}
}
func (m *ColumnEncoding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ColumnEncoding.Unmarshal(m, b)
}
func (m *ColumnEncoding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ColumnEncoding.Marshal(b, m, deterministic)
}
func (m *ColumnEncoding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ColumnEncoding.Merge(m, src)
}
func (m *ColumnEncoding) XXX_Size() int {
	return xxx_messageInfo_ColumnEncoding.Size(m)
}
func (m *ColumnEncoding) XXX_DiscardUnknown() {
	xxx_messageInfo_ColumnEncoding.DiscardUnknown(m)
}

var xxx_messageInfo_ColumnEncoding proto.InternalMessageInfo

func (m *ColumnEncoding) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ColumnEncoding) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ColumnEncoding) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type BuildInfo struct {
	Version              string   `protobuf:"bytes,1,opt,name=Version,proto3" json:"Version,omitempty"`
	Commit               string   `protobuf:"bytes,2,opt,name=Commit,proto3" json:"Commit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildInfo) Reset()         { *m = BuildInfo{} }
func (m *BuildInfo) String() string { return proto.CompactTextString(m) }
func (*BuildInfo) ProtoMessage()    {}
func (*BuildInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{29}
}
func (m *BuildInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildInfo.Unmarshal(m, b)
}
func (m *BuildInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildInfo.Marshal(b, m, deterministic)
}
func (m *BuildInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildInfo.Merge(m, src)
}
func (m *BuildInfo) XXX_Size() int {
	return xxx_messageInfo_BuildInfo.Size(m)
}
func (m *BuildInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BuildInfo proto.InternalMessageInfo

func (m *BuildInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *BuildInfo) GetCommit() string {
	if m != nil {
		return m.Commit
	}
	return ""
}

// func init() {
// 	proto.RegisterType((*Source)(nil), "internal.Source")
// 	proto.RegisterType((*Dashboard)(nil), "internal.Dashboard")
// 	proto.RegisterType((*DashboardCell)(nil), "internal.DashboardCell")
// 	proto.RegisterMapType((map[string]*Axis)(nil), "internal.DashboardCell.AxesEntry")
// 	proto.RegisterType((*DecimalPlaces)(nil), "internal.DecimalPlaces")
// 	proto.RegisterType((*TableOptions)(nil), "internal.TableOptions")
// 	proto.RegisterType((*RenamableField)(nil), "internal.RenamableField")
// 	proto.RegisterType((*Color)(nil), "internal.Color")
// 	proto.RegisterType((*Legend)(nil), "internal.Legend")
// 	proto.RegisterType((*Axis)(nil), "internal.Axis")
// 	proto.RegisterType((*Template)(nil), "internal.Template")
// 	proto.RegisterType((*TemplateValue)(nil), "internal.TemplateValue")
// 	proto.RegisterType((*TemplateQuery)(nil), "internal.TemplateQuery")
// 	proto.RegisterType((*Server)(nil), "internal.Server")
// 	proto.RegisterType((*Layout)(nil), "internal.Layout")
// 	proto.RegisterType((*Cell)(nil), "internal.Cell")
// 	proto.RegisterMapType((map[string]*Axis)(nil), "internal.Cell.AxesEntry")
// 	proto.RegisterType((*Query)(nil), "internal.Query")
// 	proto.RegisterType((*TimeShift)(nil), "internal.TimeShift")
// 	proto.RegisterType((*Range)(nil), "internal.Range")
// 	proto.RegisterType((*AlertRule)(nil), "internal.AlertRule")
// 	proto.RegisterType((*User)(nil), "internal.User")
// 	proto.RegisterType((*Role)(nil), "internal.Role")
// 	proto.RegisterType((*Mapping)(nil), "internal.Mapping")
// 	proto.RegisterType((*Organization)(nil), "internal.Organization")
// 	proto.RegisterType((*Config)(nil), "internal.Config")
// 	proto.RegisterType((*AuthConfig)(nil), "internal.AuthConfig")
// 	proto.RegisterType((*OrganizationConfig)(nil), "internal.OrganizationConfig")
// 	proto.RegisterType((*LogViewerConfig)(nil), "internal.LogViewerConfig")
// 	proto.RegisterType((*LogViewerColumn)(nil), "internal.LogViewerColumn")
// 	proto.RegisterType((*ColumnEncoding)(nil), "internal.ColumnEncoding")
// 	proto.RegisterType((*BuildInfo)(nil), "internal.BuildInfo")
// }

// func init() { proto.RegisterFile("internal.proto", fileDescriptor_41f4a519b878ee3b) }

var fileDescriptor_41f4a519b878ee3b = []byte{
	// 1843 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0xdd, 0x6f, 0xdb, 0xc8,
	0x11, 0x07, 0x25, 0x51, 0x16, 0x47, 0xb6, 0xe3, 0x6e, 0x83, 0x3b, 0xde, 0xb5, 0x28, 0x54, 0xa2,
	0xbd, 0xba, 0x1f, 0x97, 0x1e, 0x1c, 0xf4, 0x03, 0x87, 0xbb, 0x03, 0xfc, 0x91, 0xa4, 0x4e, 0x9c,
	0xc4, 0x59, 0x3b, 0xee, 0x53, 0x71, 0x58, 0x91, 0x2b, 0x69, 0x71, 0x14, 0xc9, 0x2e, 0x49, 0xdb,
	0xec, 0xbf, 0xd0, 0xb7, 0xfe, 0x01, 0x01, 0x0a, 0xb4, 0xef, 0x45, 0xd1, 0xc7, 0x02, 0x7d, 0xef,
	0x5f, 0x55, 0xcc, 0x7e, 0x50, 0x4b, 0x59, 0x09, 0x52, 0xa0, 0xe8, 0x93, 0xf6, 0x37, 0x33, 0x9c,
	0x9d, 0x9d, 0xaf, 0x9d, 0x15, 0xec, 0x8a, 0xac, 0xe2, 0x32, 0x63, 0xe9, 0x83, 0x42, 0xe6, 0x55,
	0x4e, 0x46, 0x16, 0x47, 0x6f, 0xfa, 0x30, 0xbc, 0xc8, 0x6b, 0x19, 0x73, 0xb2, 0x0b, 0xbd, 0xd3,
	0x93, 0xd0, 0x9b, 0x78, 0xfb, 0x7d, 0xda, 0x3b, 0x3d, 0x21, 0x04, 0x06, 0x2f, 0xd8, 0x92, 0x87,
	0xbd, 0x89, 0xb7, 0x1f, 0x50, 0xb5, 0x46, 0xda, 0x65, 0x53, 0xf0, 0xb0, 0xaf, 0x69, 0xb8, 0x26,
	0x1f, 0xc3, 0xe8, 0x75, 0x89, 0xda, 0x96, 0x3c, 0x1c, 0x28, 0x7a, 0x8b, 0x91, 0x77, 0xce, 0xca,
	0xf2, 0x26, 0x97, 0x49, 0xe8, 0x6b, 0x9e, 0xc5, 0x64, 0x0f, 0xfa, 0xaf, 0xe9, 0x59, 0x38, 0x54,
	0x64, 0x5c, 0x92, 0x10, 0xb6, 0x4e, 0xf8, 0x8c, 0xd5, 0x69, 0x15, 0x6e, 0x4d, 0xbc, 0xfd, 0x11,
	0xb5, 0x10, 0xf5, 0x5c, 0xf2, 0x94, 0xcf, 0x25, 0x9b, 0x85, 0x23, 0xad, 0xc7, 0x62, 0xf2, 0x00,
	0xc8, 0x69, 0x56, 0xf2, 0xb8, 0x96, 0xfc, 0xe2, 0x1b, 0x51, 0x5c, 0x71, 0x29, 0x66, 0x4d, 0x18,
	0x28, 0x05, 0x1b, 0x38, 0xb8, 0xcb, 0x73, 0x5e, 0x31, 0xdc, 0x1b, 0x94, 0x2a, 0x0b, 0x49, 0x04,
	0xdb, 0x17, 0x0b, 0x26, 0x79, 0x72, 0xc1, 0x63, 0xc9, 0xab, 0x70, 0xac, 0xd8, 0x1d, 0x1a, 0xca,
	0xbc, 0x94, 0x73, 0x96, 0x89, 0x3f, 0xb0, 0x4a, 0xe4, 0x59, 0xb8, 0xad, 0x65, 0x5c, 0x1a, 0x7a,
	0x89, 0xe6, 0x29, 0x0f, 0x77, 0xb4, 0x97, 0x70, 0x4d, 0xbe, 0x0b, 0x81, 0x39, 0x0c, 0x3d, 0x0f,
	0x77, 0x15, 0x63, 0x45, 0x40, 0x9b, 0xae, 0xb8, 0x2c, 0x51, 0xe1, 0x3d, 0x6d, 0x93, 0x81, 0xd1,
	0x3f, 0x3c, 0x08, 0x4e, 0x58, 0xb9, 0x98, 0xe6, 0x4c, 0x26, 0xef, 0x15, 0xa3, 0x4f, 0xc1, 0x8f,
	0x79, 0x9a, 0x96, 0x61, 0x7f, 0xd2, 0xdf, 0x1f, 0x1f, 0x7c, 0xf8, 0xa0, 0x0d, 0x7e, 0xab, 0xe7,
	0x98, 0xa7, 0x29, 0xd5, 0x52, 0xe4, 0x33, 0x08, 0x2a, 0xbe, 0x2c, 0x52, 0x56, 0xf1, 0x32, 0x1c,
	0xa8, 0x4f, 0xc8, 0xea, 0x93, 0x4b, 0xc3, 0xa2, 0x2b, 0xa1, 0x3b, 0x2e, 0xf0, 0xef, 0xba, 0x20,
	0xfa, 0x93, 0x0f, 0x3b, 0x9d, 0xed, 0xc8, 0x36, 0x78, 0xb7, 0xca, 0x72, 0x9f, 0x7a, 0xb7, 0x88,
	0x1a, 0x65, 0xb5, 0x4f, 0xbd, 0x06, 0xd1, 0x8d, 0xca, 0x29, 0x9f, 0x7a, 0x37, 0x88, 0x16, 0x2a,
	0x93, 0x7c, 0xea, 0x2d, 0xc8, 0x8f, 0x61, 0xeb, 0xf7, 0x35, 0x97, 0x82, 0x97, 0xa1, 0xaf, 0xac,
	0xbb, 0xb7, 0xb2, 0xee, 0x55, 0xcd, 0x65, 0x43, 0x2d, 0x1f, 0xbd, 0xa1, 0xb2, 0x50, 0xa7, 0x94,
	0x5a, 0x23, 0xad, 0xc2, 0x8c, 0xdd, 0xd2, 0x34, 0x5c, 0x1b, 0x2f, 0xea, 0x3c, 0x42, 0x2f, 0xfe,
	0x02, 0x06, 0xec, 0x96, 0x97, 0x61, 0xa0, 0xf4, 0x7f, 0xff, 0x2d, 0x0e, 0x7b, 0x70, 0x78, 0xcb,
	0xcb, 0x47, 0x59, 0x25, 0x1b, 0xaa, 0xc4, 0xc9, 0x8f, 0x60, 0x18, 0xe7, 0x69, 0x2e, 0xcb, 0x10,
	0xd6, 0x0d, 0x3b, 0x46, 0x3a, 0x35, 0x6c, 0xb2, 0x0f, 0xc3, 0x94, 0xcf, 0x79, 0x96, 0xa8, 0x8c,
	0x1a, 0x1f, 0xec, 0xad, 0x04, 0xcf, 0x14, 0x9d, 0x1a, 0x3e, 0xf9, 0x1c, 0xb6, 0x2b, 0x36, 0x4d,
	0xf9, 0xcb, 0x02, 0xbd, 0x58, 0xaa, 0xec, 0x1a, 0x1f, 0x7c, 0xe0, 0xc4, 0xc3, 0xe1, 0xd2, 0x8e,
	0x2c, 0xf9, 0x02, 0xb6, 0x67, 0x82, 0xa7, 0x89, 0xfd, 0x76, 0x47, 0x19, 0x15, 0xae, 0xbe, 0xa5,
	0x3c, 0x63, 0x4b, 0xfc, 0xe2, 0x31, 0x8a, 0xd1, 0x8e, 0x34, 0xf9, 0x1e, 0x40, 0x25, 0x96, 0xfc,
	0x71, 0x2e, 0x97, 0xac, 0x32, 0x09, 0xea, 0x50, 0xc8, 0x97, 0xb0, 0x93, 0xf0, 0x58, 0x2c, 0x59,
	0x7a, 0x9e, 0xb2, 0x98, 0x97, 0x2a, 0x4f, 0xbb, 0xd9, 0xe5, 0xb2, 0x69, 0x57, 0x5a, 0x85, 0x26,
	0xaf, 0x78, 0xb8, 0x67, 0x42, 0x93, 0x57, 0x9c, 0x7c, 0x02, 0xbb, 0xf8, 0x7b, 0x25, 0x4a, 0x31,
	0x15, 0xa9, 0xa8, 0x9a, 0xf0, 0x5b, 0x8a, 0xbb, 0x46, 0xfd, 0xf8, 0x09, 0x04, 0xad, 0xeb, 0xb1,
	0x6b, 0x7c, 0xc3, 0x1b, 0x95, 0x48, 0x01, 0xc5, 0x25, 0xf9, 0x01, 0xf8, 0xd7, 0x2c, 0xad, 0x75,
	0x11, 0x8c, 0x0f, 0x76, 0x57, 0x16, 0x1d, 0xde, 0x8a, 0x92, 0x6a, 0xe6, 0xe7, 0xbd, 0x5f, 0x7b,
	0xd1, 0x13, 0xd8, 0xe9, 0x18, 0x89, 0x87, 0x16, 0xe5, 0xa3, 0x6c, 0x96, 0xcb, 0x98, 0x27, 0x4a,
	0xe7, 0x88, 0x3a, 0x14, 0xf2, 0x01, 0x0c, 0x13, 0x31, 0x17, 0x55, 0x69, 0x52, 0xd5, 0xa0, 0xe8,
	0x9f, 0x1e, 0x6c, 0xbb, 0x91, 0x20, 0x3f, 0x81, 0xbd, 0x6b, 0x2e, 0x2b, 0x11, 0xb3, 0xf4, 0x52,
	0x2c, 0x39, 0x6e, 0xac, 0x3e, 0x19, 0xd1, 0x3b, 0x74, 0xf2, 0x19, 0x0c, 0xcb, 0x5c, 0x56, 0x47,
	0x8d, 0xca, 0xf8, 0x77, 0x45, 0xc8, 0xc8, 0x61, 0xf7, 0xbb, 0x91, 0xac, 0x28, 0x44, 0x36, 0xb7,
	0x1d, 0xd6, 0x62, 0x74, 0xe2, 0x4c, 0xdc, 0x3e, 0x16, 0xb2, 0xac, 0x8e, 0xf3, 0xb4, 0x5e, 0x66,
	0x2a, 0xfb, 0x47, 0x74, 0x8d, 0xfa, 0x74, 0x30, 0xf2, 0xf6, 0x7a, 0x4f, 0x07, 0x23, 0x7f, 0x6f,
	0x18, 0x15, 0xb0, 0xdb, 0xdd, 0x09, 0x4b, 0xda, 0x1a, 0xa1, 0xfa, 0x89, 0x76, 0x6f, 0x87, 0x46,
	0x26, 0x30, 0x4e, 0x44, 0x59, 0xa4, 0xac, 0x71, 0x5a, 0x8e, 0x4b, 0xc2, 0x2e, 0x76, 0x8d, 0x61,
	0x4b, 0xf5, 0x05, 0x31, 0xa2, 0x16, 0x46, 0x73, 0xf0, 0x55, 0x49, 0x38, 0x0d, 0x2c, 0xb0, 0x0d,
	0x4c, 0x5d, 0x28, 0x3d, 0xe7, 0x42, 0xd9, 0x83, 0xfe, 0x6f, 0xf8, 0xad, 0xb9, 0x63, 0x70, 0xd9,
	0xb6, 0xb9, 0x81, 0xd3, 0xe6, 0xee, 0x83, 0x7f, 0xa5, 0xc2, 0xae, 0xdb, 0x8f, 0x06, 0xd1, 0x57,
	0x30, 0xd4, 0x25, 0xd5, 0x6a, 0xf6, 0x1c, 0xcd, 0x13, 0x18, 0xbf, 0x94, 0x82, 0x67, 0x95, 0x6e,
	0x5c, 0xe6, 0x08, 0x0e, 0x29, 0xfa, 0xbb, 0x07, 0x03, 0x15, 0xa5, 0x08, 0xb6, 0x53, 0x3e, 0x67,
	0x71, 0x73, 0x94, 0xd7, 0x59, 0x52, 0x86, 0xde, 0xa4, 0xbf, 0xdf, 0xa7, 0x1d, 0x1a, 0xa6, 0xc7,
	0x54, 0x73, 0x7b, 0x93, 0xfe, 0x7e, 0x40, 0x0d, 0x42, 0xd3, 0x52, 0x36, 0xe5, 0xa9, 0x39, 0x82,
	0x06, 0x28, 0x5d, 0x48, 0x3e, 0x13, 0xb7, 0xe6, 0x18, 0x06, 0x21, 0xbd, 0xac, 0x67, 0x48, 0xd7,
	0x27, 0x31, 0x08, 0x0f, 0x30, 0x65, 0x65, 0xdb, 0xcd, 0x70, 0x8d, 0x9a, 0xcb, 0x98, 0xa5, 0xb6,
	0x9d, 0x69, 0x10, 0xfd, 0xcb, 0xc3, 0xeb, 0x51, 0xb7, 0xe7, 0x3b, 0x1e, 0xfe, 0x08, 0x46, 0xd8,
	0xba, 0xbf, 0xbe, 0x66, 0xd2, 0x1c, 0x78, 0x0b, 0xf1, 0x15, 0x93, 0xe4, 0xe7, 0x30, 0x54, 0xc5,
	0xb1, 0xe1, 0xaa, 0xb0, 0xea, 0x94, 0x57, 0xa9, 0x11, 0x6b, 0x9b, 0xe9, 0xc0, 0x69, 0xa6, 0xed,
	0x61, 0x7d, 0xf7, 0xb0, 0x9f, 0x82, 0x8f, 0x5d, 0xb9, 0x51, 0xd6, 0x6f, 0xd4, 0xac, 0x7b, 0xb7,
	0x96, 0x8a, 0xe6, 0xb0, 0xd3, 0xd9, 0xb1, 0xdd, 0xc9, 0xeb, 0xee, 0xb4, 0x2a, 0xf4, 0xc0, 0x14,
	0x36, 0x16, 0x47, 0xc9, 0x53, 0x1e, 0x57, 0x3c, 0x31, 0x59, 0xd7, 0x62, 0xdb, 0x2c, 0x06, 0x6d,
	0xb3, 0x88, 0xfe, 0xec, 0xad, 0x76, 0x52, 0x16, 0x60, 0xd2, 0xc6, 0xf9, 0x72, 0xc9, 0xb2, 0xc4,
	0x6c, 0x66, 0x21, 0x7a, 0x32, 0x99, 0x9a, 0xcd, 0x7a, 0xc9, 0x14, 0xb1, 0x2c, 0x4c, 0x4c, 0x7b,
	0xb2, 0xc0, 0x6c, 0x5a, 0x72, 0x56, 0xd6, 0x92, 0x2f, 0x79, 0x56, 0x99, 0x5d, 0x5c, 0x12, 0xf9,
	0x10, 0xb6, 0x2a, 0x36, 0xff, 0x1a, 0x6d, 0x30, 0xb1, 0xad, 0xd8, 0xfc, 0x19, 0x6f, 0xc8, 0x77,
	0x20, 0x50, 0xdd, 0x57, 0xb1, 0x74, 0x80, 0x47, 0x8a, 0xf0, 0x8c, 0x37, 0xd1, 0xdf, 0x7a, 0x30,
	0xbc, 0xe0, 0xf2, 0x9a, 0xcb, 0xf7, 0xba, 0xef, 0xdd, 0xf9, 0xab, 0xff, 0x8e, 0xf9, 0x6b, 0xb0,
	0x79, 0xfe, 0xf2, 0x57, 0xf3, 0xd7, 0x7d, 0xf0, 0x2f, 0x64, 0x7c, 0x7a, 0xa2, 0x2c, 0xea, 0x53,
	0x0d, 0x30, 0x3f, 0x0f, 0xe3, 0x4a, 0x5c, 0x73, 0x33, 0x94, 0x19, 0x74, 0x67, 0x0c, 0x18, 0x6d,
	0x98, 0x84, 0xfe, 0xdb, 0xd9, 0xcc, 0x16, 0x2d, 0x38, 0x45, 0x1b, 0xc1, 0x36, 0x0e, 0x68, 0x09,
	0xab, 0xd8, 0xd3, 0x8b, 0x97, 0x2f, 0xec, 0x54, 0xe6, 0xd2, 0xa2, 0x37, 0x1e, 0x0c, 0xcf, 0x58,
	0x93, 0xd7, 0xd5, 0x9d, 0xfc, 0x9f, 0xc0, 0xf8, 0xb0, 0x28, 0x52, 0x11, 0x77, 0x6a, 0xde, 0x21,
	0xa1, 0xc4, 0x73, 0x27, 0x8e, 0xda, 0x87, 0x2e, 0x09, 0xaf, 0x98, 0x63, 0x35, 0x52, 0xe9, 0xf9,
	0xc8, 0xb9, 0x62, 0xf4, 0x24, 0xa5, 0x98, 0xe8, 0xec, 0xc3, 0xba, 0xca, 0x67, 0x69, 0x7e, 0xa3,
	0xbc, 0x3a, 0xa2, 0x2d, 0x8e, 0xfe, 0xdd, 0x83, 0xc1, 0xff, 0x6b, 0x0c, 0xda, 0x06, 0x4f, 0x98,
	0xa4, 0xf2, 0x44, 0x3b, 0x14, 0x6d, 0x39, 0x43, 0x51, 0x08, 0x5b, 0x8d, 0x64, 0xd9, 0x9c, 0x97,
	0xe1, 0x48, 0xf5, 0x35, 0x0b, 0x15, 0x47, 0x55, 0xb0, 0x9e, 0x86, 0x02, 0x6a, 0x61, 0x5b, 0x91,
	0xe0, 0x54, 0xe4, 0xcf, 0xcc, 0xe0, 0x34, 0x5e, 0x1f, 0x35, 0x36, 0xcd, 0x4b, 0xff, 0xbb, 0x7b,
	0xfc, 0x8f, 0x3d, 0xf0, 0xdb, 0xe2, 0x3d, 0xee, 0x16, 0xef, 0xf1, 0xaa, 0x78, 0x4f, 0x8e, 0x6c,
	0xf1, 0x9e, 0x1c, 0x21, 0xa6, 0xe7, 0xb6, 0x78, 0xe9, 0x39, 0x06, 0xeb, 0x89, 0xcc, 0xeb, 0xe2,
	0xa8, 0xd1, 0x51, 0x0d, 0x68, 0x8b, 0x31, 0xe3, 0x7f, 0xbb, 0xe0, 0xd2, 0xb8, 0x3a, 0xa0, 0x06,
	0x61, 0x7d, 0x9c, 0xa9, 0x56, 0xa7, 0x9d, 0xab, 0x01, 0xf9, 0x21, 0xf8, 0x14, 0x9d, 0xa7, 0x3c,
	0xdc, 0x89, 0x8b, 0x22, 0x53, 0xcd, 0x45, 0xa5, 0xfa, 0xa1, 0x65, 0x0a, 0xc5, 0x3e, 0xbb, 0x7e,
	0x0a, 0xc3, 0x8b, 0x85, 0x98, 0x55, 0x76, 0xfc, 0xfc, 0xb6, 0xd3, 0x2a, 0xc5, 0x92, 0x2b, 0x1e,
	0x35, 0x22, 0x9b, 0xea, 0x23, 0x7a, 0x05, 0x41, 0x2b, 0xb8, 0x32, 0xd1, 0x73, 0x4d, 0x24, 0x30,
	0x78, 0x9d, 0x89, 0xca, 0xb6, 0x0d, 0x5c, 0xa3, 0x03, 0x5e, 0xd5, 0x2c, 0xab, 0x70, 0xee, 0x32,
	0x6d, 0xc3, 0xe2, 0xe8, 0xa1, 0x39, 0x12, 0xaa, 0x7b, 0x5d, 0x14, 0x5c, 0x9a, 0x16, 0xa4, 0x81,
	0xda, 0x24, 0xbf, 0xe1, 0xfa, 0x3e, 0xe9, 0x53, 0x0d, 0xa2, 0xdf, 0x41, 0x70, 0x98, 0x72, 0x59,
	0xd1, 0x3a, 0xe5, 0x9b, 0xee, 0x79, 0x55, 0xbc, 0xc6, 0x02, 0x5c, 0xaf, 0xda, 0x4d, 0x7f, 0xad,
	0xdd, 0x3c, 0x63, 0x05, 0x3b, 0x3d, 0x51, 0xb9, 0xdf, 0xa7, 0x06, 0x45, 0x7f, 0xf1, 0x60, 0x80,
	0x7d, 0xcd, 0x51, 0x3d, 0x78, 0x57, 0x4f, 0x3c, 0x97, 0xf9, 0xb5, 0x48, 0xb8, 0xb4, 0x87, 0xb3,
	0x58, 0x05, 0x22, 0x5e, 0xf0, 0x76, 0x9c, 0x30, 0x08, 0xf3, 0x0f, 0x5f, 0x6a, 0xb6, 0xbe, 0x9c,
	0xfc, 0x43, 0x32, 0xd5, 0x4c, 0x1c, 0x19, 0x2f, 0xea, 0x82, 0xcb, 0xc3, 0x64, 0x29, 0xec, 0xac,
	0xe5, 0x50, 0xa2, 0xaf, 0xf4, 0xdb, 0xef, 0x4e, 0x77, 0xf4, 0x36, 0xbf, 0x13, 0xd7, 0x2d, 0x8f,
	0xfe, 0xea, 0xc1, 0xd6, 0x73, 0x33, 0xdb, 0xb9, 0xa7, 0xf0, 0xde, 0x7a, 0x8a, 0x5e, 0xe7, 0x14,
	0x07, 0x70, 0xdf, 0xca, 0x74, 0xf6, 0xd7, 0x5e, 0xd8, 0xc8, 0x33, 0x1e, 0x1d, 0xb4, 0xc1, 0x7a,
	0x9f, 0x07, 0xde, 0x65, 0x57, 0x66, 0x53, 0xc0, 0xef, 0x44, 0x65, 0x02, 0x63, 0xfb, 0xe4, 0xcd,
	0x53, 0x7b, 0x59, 0xb9, 0xa4, 0xe8, 0x00, 0x86, 0xc7, 0x79, 0x36, 0x13, 0x73, 0xb2, 0x0f, 0x83,
	0xc3, 0xba, 0x5a, 0x28, 0x8d, 0xe3, 0x83, 0xfb, 0x4e, 0x33, 0xa8, 0xab, 0x85, 0x96, 0xa1, 0x4a,
	0x22, 0xfa, 0x02, 0x60, 0x45, 0xc3, 0x1b, 0x67, 0x15, 0x8d, 0x17, 0xfc, 0x06, 0x53, 0xa6, 0x34,
	0xa3, 0xfd, 0x06, 0x4e, 0x54, 0x03, 0x71, 0xcf, 0x61, 0xb4, 0x7c, 0x02, 0xbb, 0x2e, 0xb5, 0x3d,
	0xd9, 0x1a, 0x95, 0xfc, 0x0a, 0x82, 0xb3, 0x7c, 0x7e, 0x25, 0xb8, 0xad, 0x86, 0xf1, 0xc1, 0x47,
	0xce, 0xe3, 0xce, 0xb2, 0x8c, 0xbd, 0x2b, 0xd9, 0xe8, 0x31, 0xdc, 0x5b, 0xe3, 0x92, 0x87, 0xd8,
	0xcb, 0x70, 0x56, 0xd7, 0xc3, 0xe6, 0xdb, 0x34, 0xa1, 0x04, 0xb5, 0x92, 0x51, 0xd3, 0xd1, 0x83,
	0xb4, 0xd6, 0xf3, 0xde, 0x5a, 0x3d, 0xe4, 0xa5, 0x68, 0x6f, 0x40, 0x9f, 0xb6, 0x98, 0xfc, 0x12,
	0x82, 0x47, 0x59, 0x9c, 0x27, 0x22, 0x9b, 0xdb, 0x41, 0x30, 0xec, 0xbc, 0x64, 0xeb, 0x65, 0x66,
	0x05, 0xe8, 0x4a, 0x34, 0x7a, 0x01, 0xbb, 0x5d, 0xe6, 0xc6, 0x91, 0xbb, 0x1d, 0xd3, 0x7b, 0xce,
	0x98, 0xde, 0xda, 0xd8, 0x77, 0x32, 0xff, 0x4b, 0x08, 0x8e, 0x6a, 0x91, 0x26, 0xa7, 0xd9, 0x2c,
	0x77, 0xff, 0x10, 0xf1, 0x3a, 0x7f, 0x88, 0x60, 0xe2, 0x63, 0x8f, 0x6f, 0xbb, 0x99, 0x41, 0xd3,
	0xa1, 0xfa, 0x6b, 0xeb, 0xe1, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x08, 0x42, 0x4c, 0x95, 0xec,
	0x12, 0x00, 0x00,
}
