package server

import (
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	cloudhub "github.com/snetsystems/cloudhub/backend"
)

type libraryCellLinks struct {
	Self string `json:"self"` // Self link mapping to this resource
}

type libraryCellResponse struct {
	ID           string                   `json:"id"`
	Name         string                   `json:"name"`
	Description  string                   `json:"description,omitempty"`
	Organization string                   `json:"organization"`
	Type         string                   `json:"type"`
	Content      cloudhub.DashboardCell   `json:"content"`
	Meta         cloudhub.LibraryCellMeta `json:"meta"`
	Links        libraryCellLinks         `json:"links"`
}

type getLibraryCellsResponse struct {
	LibraryCells []libraryCellResponse `json:"libraryCells"`
}

func newLibraryCellResponse(cell cloudhub.LibraryCell) libraryCellResponse {
	base := "/cloudhub/v1/cell-library"
	return libraryCellResponse{
		ID:           cell.ID,
		Name:         cell.Name,
		Description:  cell.Description,
		Organization: cell.Organization,
		Type:         cell.Type,
		Content:      cell.Content,
		Meta:         cell.Meta,
		Links: libraryCellLinks{
			Self: fmt.Sprintf("%s/%s", base, cell.ID),
		},
	}
}

// CellLibrary returns all library cells within the store
func (s *Service) CellLibrary(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	cells, err := s.Store.CellLibrary(ctx).All(ctx)
	if err != nil {
		Error(w, http.StatusInternalServerError, "Error loading cell library", s.Logger)
		return
	}

	res := getLibraryCellsResponse{
		LibraryCells: []libraryCellResponse{},
	}

	for _, cell := range cells {
		res.LibraryCells = append(res.LibraryCells, newLibraryCellResponse(cell))
	}
	encodeJSON(w, http.StatusOK, res, s.Logger)
}

// LibraryCellID returns a single specified library cell
func (s *Service) LibraryCellID(w http.ResponseWriter, r *http.Request) {
	id, err := paramStr("id", r)
	if err != nil {
		Error(w, http.StatusUnprocessableEntity, err.Error(), s.Logger)
		return
	}

	ctx := r.Context()
	cell, err := s.Store.CellLibrary(ctx).Get(ctx, id)
	if err != nil {
		Error(w, http.StatusNotFound, "Library cell not found", s.Logger)
		return
	}

	res := newLibraryCellResponse(cell)
	encodeJSON(w, http.StatusOK, res, s.Logger)
}

// NewLibraryCell creates and returns a new library cell
func (s *Service) NewLibraryCell(w http.ResponseWriter, r *http.Request) {
	var cell cloudhub.LibraryCell
	if err := json.NewDecoder(r.Body).Decode(&cell); err != nil {
		invalidJSON(w, s.Logger)
		return
	}

	ctx := r.Context()

	// Validate required fields
	if cell.Name == "" {
		invalidData(w, fmt.Errorf("name is required"), s.Logger)
		return
	}
	if cell.Type == "" {
		invalidData(w, fmt.Errorf("type is required"), s.Logger)
		return
	}

	// Set UpdatedAt on create
	cell.Meta.UpdatedAt = time.Now().UTC().Format(time.RFC3339)

	// ID will be generated by the store if not provided
	var err error
	if cell, err = s.Store.CellLibrary(ctx).Add(ctx, cell); err != nil {
		msg := fmt.Errorf("Error storing library cell %v: %v", cell.Name, err)
		unknownErrorWithMessage(w, msg, s.Logger)
		return
	}

	// log registration
	msg := fmt.Sprintf("Library cell '%s' created", cell.Name)
	s.logRegistration(ctx, "CellLibrary", msg)

	res := newLibraryCellResponse(cell)
	location(w, res.Links.Self)
	encodeJSON(w, http.StatusCreated, res, s.Logger)
}

// RemoveLibraryCell deletes a library cell
func (s *Service) RemoveLibraryCell(w http.ResponseWriter, r *http.Request) {
	id, err := paramStr("id", r)
	if err != nil {
		Error(w, http.StatusUnprocessableEntity, err.Error(), s.Logger)
		return
	}

	ctx := r.Context()
	cell, err := s.Store.CellLibrary(ctx).Get(ctx, id)
	if err != nil {
		Error(w, http.StatusNotFound, "Library cell not found", s.Logger)
		return
	}

	if err := s.Store.CellLibrary(ctx).Delete(ctx, cell); err != nil {
		unknownErrorWithMessage(w, err, s.Logger)
		return
	}

	// log registration
	msg := fmt.Sprintf("Library cell '%s' deleted", cell.Name)
	s.logRegistration(ctx, "CellLibrary", msg)

	w.WriteHeader(http.StatusNoContent)
}

// UpdateLibraryCell completely replaces a library cell
func (s *Service) UpdateLibraryCell(w http.ResponseWriter, r *http.Request) {
	id, err := paramStr("id", r)
	if err != nil {
		Error(w, http.StatusUnprocessableEntity, err.Error(), s.Logger)
		return
	}

	ctx := r.Context()
	existing, err := s.Store.CellLibrary(ctx).Get(ctx, id)
	if err != nil {
		Error(w, http.StatusNotFound, "Library cell not found", s.Logger)
		return
	}

	var cell cloudhub.LibraryCell
	if err := json.NewDecoder(r.Body).Decode(&cell); err != nil {
		invalidJSON(w, s.Logger)
		return
	}

	// Preserve ID and organization, set UpdatedAt
	cell.ID = existing.ID
	cell.Organization = existing.Organization
	cell.Meta.UpdatedAt = time.Now().UTC().Format(time.RFC3339)

	if err := s.Store.CellLibrary(ctx).Update(ctx, cell); err != nil {
		msg := fmt.Errorf("Error updating library cell %s: %v", id, err)
		unknownErrorWithMessage(w, msg, s.Logger)
		return
	}

	// log registration
	msg := fmt.Sprintf("Library cell '%s' updated", cell.Name)
	s.logRegistration(ctx, "CellLibrary", msg)

	res := newLibraryCellResponse(cell)
	encodeJSON(w, http.StatusOK, res, s.Logger)
}

// PatchLibraryCell partially updates a library cell
func (s *Service) PatchLibraryCell(w http.ResponseWriter, r *http.Request) {
	id, err := paramStr("id", r)
	if err != nil {
		Error(w, http.StatusUnprocessableEntity, err.Error(), s.Logger)
		return
	}

	ctx := r.Context()
	existing, err := s.Store.CellLibrary(ctx).Get(ctx, id)
	if err != nil {
		Error(w, http.StatusNotFound, "Library cell not found", s.Logger)
		return
	}

	var patch map[string]interface{}
	if err := json.NewDecoder(r.Body).Decode(&patch); err != nil {
		invalidJSON(w, s.Logger)
		return
	}

	// Apply patch fields
	if name, ok := patch["name"].(string); ok {
		existing.Name = name
	}
	if description, ok := patch["description"].(string); ok {
		existing.Description = description
	}
	if cellType, ok := patch["type"].(string); ok {
		existing.Type = cellType
	}
	if content, ok := patch["content"]; ok {
		contentBytes, err := json.Marshal(content)
		if err != nil {
			invalidData(w, fmt.Errorf("invalid content format"), s.Logger)
			return
		}
		var c cloudhub.DashboardCell
		if err := json.Unmarshal(contentBytes, &c); err != nil {
			invalidData(w, fmt.Errorf("invalid content format"), s.Logger)
			return
		}
		existing.Content = c
	}

	existing.Meta.UpdatedAt = time.Now().UTC().Format(time.RFC3339)

	if err := s.Store.CellLibrary(ctx).Update(ctx, existing); err != nil {
		msg := fmt.Errorf("Error updating library cell %s: %v", id, err)
		unknownErrorWithMessage(w, msg, s.Logger)
		return
	}

	// log registration
	msg := fmt.Sprintf("Library cell '%s' updated", existing.Name)
	s.logRegistration(ctx, "CellLibrary", msg)

	res := newLibraryCellResponse(existing)
	encodeJSON(w, http.StatusOK, res, s.Logger)
}
