export const ROUTER_TABLE_SIZING = {
  ASSETID: '10%',
  ROUTERSTATUS: '10%',
  NETWORKSTATUS: '8%',
  APPLICATIONSTATUS: '10%',
  CPU: '5%',
  MEMORY: '5%',
  SDPLEXTRAFFICUSAGE: '12%',
  CONFIG: '20%',
  FIRMWARE: '20%',
}

export const TOPSOURCES_TABLE_SIZING = {
  IP: '20%',
  TENANT: '20%',
  CURRENTBANDWIDTH: '20%',
  TOTALDATA: '20%',
  SESSIONCOUNT: '20%',
}
