export const ROUTER_TABLE_SIZING = {
  ASSETID: '10%',
  ROUTERSTATUS: '10%',
  NETWORKSTATUS: '8%',
  APPLICATIONSTATUS: '10%',
  CPU: '5%',
  MEMORY: '5%',
  SDPLEXTRAFFICUSAGE: '12%',
  CONFIG: '20%',
  FIRMWARE: '20%',
}
